-- Oracle schema for the chess association website.
-- The model is intentionally normalized close to BCNF:
-- 1. lookups are isolated in dedicated tables
-- 2. account/profile/content/media/order concerns are separated
-- 3. media binaries and external storage references are separated

CREATE TABLE account_role (
    account_role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR2(30 CHAR) NOT NULL,
    role_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_account_role_code UNIQUE (role_code),
    CONSTRAINT uq_account_role_label UNIQUE (role_label)
);

CREATE TABLE account_status (
    account_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR2(30 CHAR) NOT NULL,
    status_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_account_status_code UNIQUE (status_code)
);

CREATE TABLE publication_status (
    publication_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR2(30 CHAR) NOT NULL,
    status_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_publication_status_code UNIQUE (status_code)
);

CREATE TABLE review_decision_type (
    review_decision_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_code VARCHAR2(30 CHAR) NOT NULL,
    decision_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_review_decision_type_code UNIQUE (decision_code)
);

CREATE TABLE consent_type (
    consent_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_code VARCHAR2(50 CHAR) NOT NULL,
    consent_label VARCHAR2(150 CHAR) NOT NULL,
    legal_basis VARCHAR2(150 CHAR) NOT NULL,
    retention_months NUMBER(4) NOT NULL,
    is_required CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_consent_type_code UNIQUE (consent_code),
    CONSTRAINT ck_consent_type_required CHECK (is_required IN ('Y', 'N'))
);

CREATE TABLE media_type (
    media_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type_code VARCHAR2(30 CHAR) NOT NULL,
    media_type_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_type_code UNIQUE (media_type_code)
);

CREATE TABLE media_usage_type (
    media_usage_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_code VARCHAR2(40 CHAR) NOT NULL,
    usage_label VARCHAR2(120 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_usage_type_code UNIQUE (usage_code)
);

CREATE TABLE media_rights_status (
    media_rights_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR2(30 CHAR) NOT NULL,
    status_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_rights_status_code UNIQUE (status_code)
);

CREATE TABLE media_storage_mode (
    media_storage_mode_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_mode_code VARCHAR2(30 CHAR) NOT NULL,
    storage_mode_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_storage_mode_code UNIQUE (storage_mode_code)
);

CREATE TABLE product_category (
    product_category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR2(30 CHAR) NOT NULL,
    category_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_product_category_code UNIQUE (category_code)
);

CREATE TABLE product_status (
    product_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR2(30 CHAR) NOT NULL,
    status_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_product_status_code UNIQUE (status_code)
);

CREATE TABLE order_status (
    order_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code VARCHAR2(30 CHAR) NOT NULL,
    status_label VARCHAR2(100 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_order_status_code UNIQUE (status_code)
);

CREATE TABLE member_account (
    member_account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_address VARCHAR2(320 CHAR) NOT NULL,
    password_hash VARCHAR2(255 CHAR) NOT NULL,
    email_verified_at TIMESTAMP WITH TIME ZONE NULL,
    account_role_id NUMBER NOT NULL,
    account_status_id NUMBER NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_member_account_role FOREIGN KEY (account_role_id) REFERENCES account_role (account_role_id),
    CONSTRAINT fk_member_account_status FOREIGN KEY (account_status_id) REFERENCES account_status (account_status_id)
);

CREATE UNIQUE INDEX uq_member_account_email_lower
    ON member_account (LOWER(email_address));

CREATE TABLE member_profile (
    member_profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id NUMBER NOT NULL,
    first_name VARCHAR2(100 CHAR) NOT NULL,
    last_name VARCHAR2(100 CHAR) NOT NULL,
    birth_date DATE NULL,
    biography CLOB NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_member_profile_account UNIQUE (member_account_id),
    CONSTRAINT fk_member_profile_account FOREIGN KEY (member_account_id) REFERENCES member_account (member_account_id)
);

CREATE TABLE visitor_cookie_consent (
    visitor_cookie_consent_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_token VARCHAR2(128 CHAR) NOT NULL,
    consent_version VARCHAR2(40 CHAR) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    theme_choice VARCHAR2(10 CHAR) NULL,
    ip_address VARCHAR2(64 CHAR) NULL,
    user_agent VARCHAR2(400 CHAR) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_visitor_cookie_consent_token UNIQUE (consent_token)
);

CREATE TABLE member_consent (
    member_consent_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id NUMBER NOT NULL,
    consent_type_id NUMBER NOT NULL,
    consent_version VARCHAR2(40 CHAR) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address VARCHAR2(64 CHAR) NULL,
    user_agent VARCHAR2(400 CHAR) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_member_consent UNIQUE (member_account_id, consent_type_id, consent_version),
    CONSTRAINT fk_member_consent_account FOREIGN KEY (member_account_id) REFERENCES member_account (member_account_id),
    CONSTRAINT fk_member_consent_type FOREIGN KEY (consent_type_id) REFERENCES consent_type (consent_type_id)
);

CREATE TABLE article (
    article_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_account_id NUMBER NOT NULL,
    publication_status_id NUMBER NOT NULL,
    title VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    excerpt VARCHAR2(500 CHAR) NOT NULL,
    body_content CLOB NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_author FOREIGN KEY (author_account_id) REFERENCES member_account (member_account_id),
    CONSTRAINT fk_article_status FOREIGN KEY (publication_status_id) REFERENCES publication_status (publication_status_id)
);

CREATE TABLE article_review (
    article_review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id NUMBER NOT NULL,
    reviewer_account_id NUMBER NOT NULL,
    review_decision_type_id NUMBER NOT NULL,
    review_comment CLOB NULL,
    decided_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_article_review_article FOREIGN KEY (article_id) REFERENCES article (article_id),
    CONSTRAINT fk_article_review_reviewer FOREIGN KEY (reviewer_account_id) REFERENCES member_account (member_account_id),
    CONSTRAINT fk_article_review_decision FOREIGN KEY (review_decision_type_id) REFERENCES review_decision_type (review_decision_type_id)
);

CREATE TABLE media_asset (
    media_asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type_id NUMBER NOT NULL,
    media_storage_mode_id NUMBER NOT NULL,
    uploaded_by_account_id NUMBER NULL,
    original_filename VARCHAR2(255 CHAR) NOT NULL,
    mime_type VARCHAR2(120 CHAR) NOT NULL,
    byte_size NUMBER(19) NOT NULL,
    width_px NUMBER(10) NULL,
    height_px NUMBER(10) NULL,
    duration_seconds NUMBER(10,3) NULL,
    alt_text VARCHAR2(300 CHAR) NULL,
    capture_date DATE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_media_asset_type FOREIGN KEY (media_type_id) REFERENCES media_type (media_type_id),
    CONSTRAINT fk_media_asset_storage_mode FOREIGN KEY (media_storage_mode_id) REFERENCES media_storage_mode (media_storage_mode_id),
    CONSTRAINT fk_media_asset_uploader FOREIGN KEY (uploaded_by_account_id) REFERENCES member_account (member_account_id)
);

CREATE TABLE media_binary_payload (
    media_binary_payload_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_asset_id NUMBER NOT NULL,
    payload_blob BLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_binary_payload_asset UNIQUE (media_asset_id),
    CONSTRAINT fk_media_binary_payload_asset FOREIGN KEY (media_asset_id) REFERENCES media_asset (media_asset_id)
);

CREATE TABLE media_external_reference (
    media_external_reference_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_asset_id NUMBER NOT NULL,
    storage_provider VARCHAR2(60 CHAR) NOT NULL,
    storage_uri VARCHAR2(1000 CHAR) NOT NULL,
    checksum_sha256 CHAR(64 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_external_reference_asset UNIQUE (media_asset_id),
    CONSTRAINT uq_media_external_reference_uri UNIQUE (storage_uri),
    CONSTRAINT uq_media_external_reference_checksum UNIQUE (checksum_sha256),
    CONSTRAINT fk_media_external_reference_asset FOREIGN KEY (media_asset_id) REFERENCES media_asset (media_asset_id)
);

CREATE TABLE media_rights_grant (
    media_rights_grant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_asset_id NUMBER NOT NULL,
    media_rights_status_id NUMBER NOT NULL,
    rights_holder_name VARCHAR2(200 CHAR) NOT NULL,
    consent_reference VARCHAR2(200 CHAR) NULL,
    grant_scope VARCHAR2(200 CHAR) NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NULL,
    review_comment VARCHAR2(500 CHAR) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_media_rights_grant_asset FOREIGN KEY (media_asset_id) REFERENCES media_asset (media_asset_id),
    CONSTRAINT fk_media_rights_grant_status FOREIGN KEY (media_rights_status_id) REFERENCES media_rights_status (media_rights_status_id)
);

CREATE TABLE media_album (
    media_album_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_account_id NUMBER NOT NULL,
    title VARCHAR2(200 CHAR) NOT NULL,
    description CLOB NULL,
    is_public CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_media_album_is_public CHECK (is_public IN ('Y', 'N')),
    CONSTRAINT fk_media_album_creator FOREIGN KEY (created_by_account_id) REFERENCES member_account (member_account_id)
);

CREATE TABLE media_album_item (
    media_album_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_album_id NUMBER NOT NULL,
    media_asset_id NUMBER NOT NULL,
    display_order NUMBER(6) DEFAULT 1 NOT NULL,
    caption VARCHAR2(300 CHAR) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_album_item UNIQUE (media_album_id, media_asset_id),
    CONSTRAINT fk_media_album_item_album FOREIGN KEY (media_album_id) REFERENCES media_album (media_album_id),
    CONSTRAINT fk_media_album_item_asset FOREIGN KEY (media_asset_id) REFERENCES media_asset (media_asset_id)
);

CREATE TABLE article_media (
    article_media_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id NUMBER NOT NULL,
    media_asset_id NUMBER NOT NULL,
    media_usage_type_id NUMBER NOT NULL,
    display_order NUMBER(6) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_article_media UNIQUE (article_id, media_asset_id, media_usage_type_id),
    CONSTRAINT fk_article_media_article FOREIGN KEY (article_id) REFERENCES article (article_id),
    CONSTRAINT fk_article_media_asset FOREIGN KEY (media_asset_id) REFERENCES media_asset (media_asset_id),
    CONSTRAINT fk_article_media_usage FOREIGN KEY (media_usage_type_id) REFERENCES media_usage_type (media_usage_type_id)
);

CREATE TABLE product (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id NUMBER NOT NULL,
    product_status_id NUMBER NOT NULL,
    title VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    sku VARCHAR2(80 CHAR) NULL,
    short_description VARCHAR2(500 CHAR) NOT NULL,
    long_description CLOB NULL,
    stock_quantity NUMBER(10) DEFAULT 0 NOT NULL,
    available_from TIMESTAMP WITH TIME ZONE NULL,
    available_until TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_product_slug UNIQUE (slug),
    CONSTRAINT uq_product_sku UNIQUE (sku),
    CONSTRAINT fk_product_category FOREIGN KEY (product_category_id) REFERENCES product_category (product_category_id),
    CONSTRAINT fk_product_status FOREIGN KEY (product_status_id) REFERENCES product_status (product_status_id)
);

CREATE TABLE product_price (
    product_price_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    currency_code CHAR(3 CHAR) NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    effective_from TIMESTAMP WITH TIME ZONE NOT NULL,
    effective_to TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_product_price UNIQUE (product_id, currency_code, effective_from),
    CONSTRAINT ck_product_price_amount CHECK (amount >= 0),
    CONSTRAINT fk_product_price_product FOREIGN KEY (product_id) REFERENCES product (product_id)
);

CREATE TABLE product_media (
    product_media_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    media_asset_id NUMBER NOT NULL,
    media_usage_type_id NUMBER NOT NULL,
    display_order NUMBER(6) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_product_media UNIQUE (product_id, media_asset_id, media_usage_type_id),
    CONSTRAINT fk_product_media_product FOREIGN KEY (product_id) REFERENCES product (product_id),
    CONSTRAINT fk_product_media_asset FOREIGN KEY (media_asset_id) REFERENCES media_asset (media_asset_id),
    CONSTRAINT fk_product_media_usage FOREIGN KEY (media_usage_type_id) REFERENCES media_usage_type (media_usage_type_id)
);

CREATE TABLE customer_order (
    customer_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id NUMBER NULL,
    order_status_id NUMBER NOT NULL,
    order_reference VARCHAR2(50 CHAR) NOT NULL,
    billing_name VARCHAR2(200 CHAR) NOT NULL,
    billing_email VARCHAR2(320 CHAR) NOT NULL,
    currency_code CHAR(3 CHAR) NOT NULL,
    placed_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE NULL,
    canceled_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_order_reference UNIQUE (order_reference),
    CONSTRAINT fk_customer_order_account FOREIGN KEY (member_account_id) REFERENCES member_account (member_account_id),
    CONSTRAINT fk_customer_order_status FOREIGN KEY (order_status_id) REFERENCES order_status (order_status_id)
);

CREATE TABLE customer_order_item (
    customer_order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_customer_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_customer_order_item_unit_price CHECK (unit_price >= 0),
    CONSTRAINT fk_customer_order_item_order FOREIGN KEY (customer_order_id) REFERENCES customer_order (customer_order_id),
    CONSTRAINT fk_customer_order_item_product FOREIGN KEY (product_id) REFERENCES product (product_id)
);
