-- Oracle schema for the chess association website.
-- The model is intentionally normalized close to BCNF:
-- 1. lookups are isolated in dedicated tables
-- 2. account/profile/content/media/order concerns are separated
-- 3. media binaries and external storage references are separated

CREATE TABLE role_compte (
    identifiant_role_compte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_role VARCHAR2(30 CHAR) NOT NULL,
    libelle_role VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_role_compte_code UNIQUE (code_role),
    CONSTRAINT uq_role_compte_label UNIQUE (libelle_role)
);

CREATE TABLE statut_compte (
    identifiant_statut_compte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_compte_code UNIQUE (code_statut)
);

CREATE TABLE statut_publication (
    identifiant_statut_publication NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_publication_code UNIQUE (code_statut)
);

CREATE TABLE type_decision_revision (
    identifiant_type_decision_revision NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_decision VARCHAR2(30 CHAR) NOT NULL,
    libelle_decision VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_decision_revision_code UNIQUE (code_decision)
);

CREATE TABLE type_consentement (
    identifiant_type_consentement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_consentement VARCHAR2(50 CHAR) NOT NULL,
    libelle_consentement VARCHAR2(150 CHAR) NOT NULL,
    base_legale VARCHAR2(150 CHAR) NOT NULL,
    duree_conservation_mois NUMBER(4) NOT NULL,
    est_obligatoire CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_consentement_code UNIQUE (code_consentement),
    CONSTRAINT ck_type_consentement_required CHECK (est_obligatoire IN ('Y', 'N'))
);

CREATE TABLE type_media (
    identifiant_type_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_media VARCHAR2(30 CHAR) NOT NULL,
    libelle_type_media VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_code_type_media UNIQUE (code_type_media)
);

CREATE TABLE type_usage_media (
    identifiant_type_usage_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_usage VARCHAR2(40 CHAR) NOT NULL,
    libelle_usage VARCHAR2(120 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_usage_media_code UNIQUE (code_usage)
);

CREATE TABLE statut_droits_media (
    identifiant_statut_droits_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_droits_media_code UNIQUE (code_statut)
);

CREATE TABLE mode_stockage_media (
    identifiant_mode_stockage_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_mode_stockage VARCHAR2(30 CHAR) NOT NULL,
    libelle_mode_stockage VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_mode_stockage_media_code UNIQUE (code_mode_stockage)
);

CREATE TABLE categorie_produit (
    identifiant_categorie_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_categorie VARCHAR2(30 CHAR) NOT NULL,
    libelle_categorie VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_categorie_produit_code UNIQUE (code_categorie)
);

CREATE TABLE statut_produit (
    identifiant_statut_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_produit_code UNIQUE (code_statut)
);

CREATE TABLE statut_commande (
    identifiant_statut_commande NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_commande_code UNIQUE (code_statut)
);

CREATE TABLE compte_membre (
    identifiant_compte_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adresse_courriel VARCHAR2(320 CHAR) NOT NULL,
    mot_de_passe_hache VARCHAR2(255 CHAR) NOT NULL,
    courriel_verifie_le TIMESTAMP WITH TIME ZONE NULL,
    identifiant_role_compte NUMBER NOT NULL,
    identifiant_statut_compte NUMBER NOT NULL,
    derniere_connexion_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_compte_membre_role FOREIGN KEY (identifiant_role_compte) REFERENCES role_compte (identifiant_role_compte),
    CONSTRAINT fk_compte_membre_status FOREIGN KEY (identifiant_statut_compte) REFERENCES statut_compte (identifiant_statut_compte)
);

CREATE UNIQUE INDEX uq_compte_membre_email_lower
    ON compte_membre (LOWER(adresse_courriel));

CREATE TABLE profil_membre (
    identifiant_profil_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    prenom VARCHAR2(100 CHAR) NOT NULL,
    nom VARCHAR2(100 CHAR) NOT NULL,
    date_naissance DATE NULL,
    biographie CLOB NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_profil_membre_account UNIQUE (identifiant_compte_membre),
    CONSTRAINT fk_profil_membre_account FOREIGN KEY (identifiant_compte_membre) REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE consentement_cookie_visiteur (
    identifiant_consentement_cookie_visiteur NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jeton_consentement VARCHAR2(128 CHAR) NOT NULL,
    version_consentement VARCHAR2(40 CHAR) NOT NULL,
    accepte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    choix_theme VARCHAR2(10 CHAR) NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_consentement_cookie_visiteur_token UNIQUE (jeton_consentement)
);

CREATE TABLE consentement_membre (
    identifiant_consentement_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_type_consentement NUMBER NOT NULL,
    version_consentement VARCHAR2(40 CHAR) NOT NULL,
    accepte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_consentement_membre UNIQUE (identifiant_compte_membre, identifiant_type_consentement, version_consentement),
    CONSTRAINT fk_consentement_membre_account FOREIGN KEY (identifiant_compte_membre) REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_consentement_membre_type FOREIGN KEY (identifiant_type_consentement) REFERENCES type_consentement (identifiant_type_consentement)
);

CREATE TABLE article (
    identifiant_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_auteur NUMBER NOT NULL,
    identifiant_statut_publication NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    resume VARCHAR2(500 CHAR) NOT NULL,
    contenu CLOB NOT NULL,
    soumis_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    publie_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_author FOREIGN KEY (identifiant_compte_auteur) REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_article_status FOREIGN KEY (identifiant_statut_publication) REFERENCES statut_publication (identifiant_statut_publication)
);

CREATE TABLE revision_article (
    identifiant_revision_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    identifiant_compte_relecteur NUMBER NOT NULL,
    identifiant_type_decision_revision NUMBER NOT NULL,
    commentaire_revision CLOB NULL,
    decide_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_revision_article_article FOREIGN KEY (identifiant_article) REFERENCES article (identifiant_article),
    CONSTRAINT fk_revision_article_reviewer FOREIGN KEY (identifiant_compte_relecteur) REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_revision_article_decision FOREIGN KEY (identifiant_type_decision_revision) REFERENCES type_decision_revision (identifiant_type_decision_revision)
);

CREATE TABLE ressource_media (
    identifiant_ressource_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_type_media NUMBER NOT NULL,
    identifiant_mode_stockage_media NUMBER NOT NULL,
    identifiant_compte_depot NUMBER NULL,
    nom_fichier_original VARCHAR2(255 CHAR) NOT NULL,
    type_mime VARCHAR2(120 CHAR) NOT NULL,
    taille_octets NUMBER(19) NOT NULL,
    largeur_px NUMBER(10) NULL,
    hauteur_px NUMBER(10) NULL,
    duree_secondes NUMBER(10,3) NULL,
    texte_alternatif VARCHAR2(300 CHAR) NULL,
    date_capture DATE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ressource_type_media FOREIGN KEY (identifiant_type_media) REFERENCES type_media (identifiant_type_media),
    CONSTRAINT fk_ressource_media_storage_mode FOREIGN KEY (identifiant_mode_stockage_media) REFERENCES mode_stockage_media (identifiant_mode_stockage_media),
    CONSTRAINT fk_ressource_media_uploader FOREIGN KEY (identifiant_compte_depot) REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE charge_binaire_media (
    identifiant_charge_binaire_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    charge_binaire BLOB NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_charge_binaire_ressource_media UNIQUE (identifiant_ressource_media),
    CONSTRAINT fk_charge_binaire_ressource_media FOREIGN KEY (identifiant_ressource_media) REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE reference_externe_media (
    identifiant_reference_externe_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    fournisseur_stockage VARCHAR2(60 CHAR) NOT NULL,
    uri_stockage VARCHAR2(1000 CHAR) NOT NULL,
    empreinte_sha256 CHAR(64 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_reference_externe_ressource_media UNIQUE (identifiant_ressource_media),
    CONSTRAINT uq_reference_externe_media_uri UNIQUE (uri_stockage),
    CONSTRAINT uq_reference_externe_media_checksum UNIQUE (empreinte_sha256),
    CONSTRAINT fk_reference_externe_ressource_media FOREIGN KEY (identifiant_ressource_media) REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE autorisation_droits_media (
    identifiant_autorisation_droits_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_statut_droits_media NUMBER NOT NULL,
    nom_titulaire_droits VARCHAR2(200 CHAR) NOT NULL,
    reference_consentement VARCHAR2(200 CHAR) NULL,
    perimetre_autorisation VARCHAR2(200 CHAR) NOT NULL,
    autorise_le TIMESTAMP WITH TIME ZONE NOT NULL,
    expire_le TIMESTAMP WITH TIME ZONE NULL,
    commentaire_revision VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_autorisation_droits_ressource_media FOREIGN KEY (identifiant_ressource_media) REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_autorisation_droits_media_status FOREIGN KEY (identifiant_statut_droits_media) REFERENCES statut_droits_media (identifiant_statut_droits_media)
);

CREATE TABLE album_media (
    identifiant_album_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_createur NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    description CLOB NULL,
    est_public CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_album_media_est_public CHECK (est_public IN ('Y', 'N')),
    CONSTRAINT fk_album_media_creator FOREIGN KEY (identifiant_compte_createur) REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE element_album_media (
    identifiant_element_album_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_album_media NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    legende VARCHAR2(300 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_element_album_media UNIQUE (identifiant_album_media, identifiant_ressource_media),
    CONSTRAINT fk_element_album_album_media FOREIGN KEY (identifiant_album_media) REFERENCES album_media (identifiant_album_media),
    CONSTRAINT fk_element_album_ressource_media FOREIGN KEY (identifiant_ressource_media) REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE media_article (
    identifiant_media_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_type_usage_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_article UNIQUE (identifiant_article, identifiant_ressource_media, identifiant_type_usage_media),
    CONSTRAINT fk_media_article_article FOREIGN KEY (identifiant_article) REFERENCES article (identifiant_article),
    CONSTRAINT fk_media_article_asset FOREIGN KEY (identifiant_ressource_media) REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_media_article_usage FOREIGN KEY (identifiant_type_usage_media) REFERENCES type_usage_media (identifiant_type_usage_media)
);

CREATE TABLE produit (
    identifiant_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_categorie_produit NUMBER NOT NULL,
    identifiant_statut_produit NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    reference_stock VARCHAR2(80 CHAR) NULL,
    description_courte VARCHAR2(500 CHAR) NOT NULL,
    description_longue CLOB NULL,
    quantite_stock NUMBER(10) DEFAULT 0 NOT NULL,
    disponible_a_partir_de TIMESTAMP WITH TIME ZONE NULL,
    disponible_jusqua TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_produit_slug UNIQUE (slug),
    CONSTRAINT uq_produit_reference_stock UNIQUE (reference_stock),
    CONSTRAINT fk_categorie_produit FOREIGN KEY (identifiant_categorie_produit) REFERENCES categorie_produit (identifiant_categorie_produit),
    CONSTRAINT fk_statut_produit FOREIGN KEY (identifiant_statut_produit) REFERENCES statut_produit (identifiant_statut_produit)
);

CREATE TABLE prix_produit (
    identifiant_prix_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_produit NUMBER NOT NULL,
    code_devise CHAR(3 CHAR) NOT NULL,
    montant NUMBER(10,2) NOT NULL,
    applicable_a_partir_de TIMESTAMP WITH TIME ZONE NOT NULL,
    applicable_jusqua TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_prix_produit UNIQUE (identifiant_produit, code_devise, applicable_a_partir_de),
    CONSTRAINT ck_prix_produit_montant CHECK (montant >= 0),
    CONSTRAINT fk_prix_produit_produit FOREIGN KEY (identifiant_produit) REFERENCES produit (identifiant_produit)
);

CREATE TABLE media_produit (
    identifiant_media_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_produit NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_type_usage_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_produit UNIQUE (identifiant_produit, identifiant_ressource_media, identifiant_type_usage_media),
    CONSTRAINT fk_media_produit_produit FOREIGN KEY (identifiant_produit) REFERENCES produit (identifiant_produit),
    CONSTRAINT fk_produit_ressource_media FOREIGN KEY (identifiant_ressource_media) REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_media_produit_usage FOREIGN KEY (identifiant_type_usage_media) REFERENCES type_usage_media (identifiant_type_usage_media)
);

CREATE TABLE commande_client (
    identifiant_commande_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NULL,
    identifiant_statut_commande NUMBER NOT NULL,
    reference_commande VARCHAR2(50 CHAR) NOT NULL,
    nom_facturation VARCHAR2(200 CHAR) NOT NULL,
    courriel_facturation VARCHAR2(320 CHAR) NOT NULL,
    code_devise CHAR(3 CHAR) NOT NULL,
    commandee_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    payee_le TIMESTAMP WITH TIME ZONE NULL,
    annulee_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_commande_client_reference UNIQUE (reference_commande),
    CONSTRAINT fk_commande_client_account FOREIGN KEY (identifiant_compte_membre) REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_commande_client_status FOREIGN KEY (identifiant_statut_commande) REFERENCES statut_commande (identifiant_statut_commande)
);

CREATE TABLE ligne_commande_client (
    identifiant_ligne_commande_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_commande_client NUMBER NOT NULL,
    identifiant_produit NUMBER NOT NULL,
    quantite NUMBER(10) NOT NULL,
    prix_unitaire NUMBER(10,2) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_ligne_commande_client_quantite CHECK (quantite > 0),
    CONSTRAINT ck_ligne_commande_client_prix_unitaire CHECK (prix_unitaire >= 0),
    CONSTRAINT fk_ligne_commande_client_order FOREIGN KEY (identifiant_commande_client) REFERENCES commande_client (identifiant_commande_client),
    CONSTRAINT fk_ligne_commande_client_produit FOREIGN KEY (identifiant_produit) REFERENCES produit (identifiant_produit)
);



