-- ============================================================
-- BDD_echec_v1.sql
-- Base Oracle complete pour un site de club d'echecs
-- (comptes, profil, conformite, articles, mediatheque,
--  boutique, adhesions, activites, tournois, maintenance)
-- ============================================================

SET DEFINE OFF;

-- ============================================================
-- 1) TABLES DE REFERENCE
-- ============================================================

CREATE TABLE role_compte (
    identifiant_role_compte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_role VARCHAR2(30 CHAR) NOT NULL,
    libelle_role VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_role_compte_code UNIQUE (code_role),
    CONSTRAINT uq_role_compte_libelle UNIQUE (libelle_role)
);

CREATE TABLE statut_compte (
    identifiant_statut_compte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_compte_code UNIQUE (code_statut)
);

CREATE TABLE statut_publication (
    identifiant_statut_publication NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_publication_code UNIQUE (code_statut)
);

CREATE TABLE type_decision_revision (
    identifiant_type_decision_revision NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_decision VARCHAR2(30 CHAR) NOT NULL,
    libelle_decision VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_decision_revision_code UNIQUE (code_decision)
);

CREATE TABLE type_consentement (
    identifiant_type_consentement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_consentement VARCHAR2(50 CHAR) NOT NULL,
    libelle_consentement VARCHAR2(150 CHAR) NOT NULL,
    base_legale VARCHAR2(150 CHAR) NOT NULL,
    duree_conservation_mois NUMBER(4) NOT NULL,
    est_obligatoire CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_consentement_code UNIQUE (code_consentement),
    CONSTRAINT ck_type_consentement_obligatoire CHECK (est_obligatoire IN ('Y', 'N'))
);

CREATE TABLE type_media (
    identifiant_type_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_media VARCHAR2(30 CHAR) NOT NULL,
    libelle_type_media VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_media_code UNIQUE (code_type_media)
);

CREATE TABLE type_usage_media (
    identifiant_type_usage_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_usage VARCHAR2(40 CHAR) NOT NULL,
    libelle_usage VARCHAR2(120 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_usage_media_code UNIQUE (code_usage)
);

CREATE TABLE statut_droits_media (
    identifiant_statut_droits_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_droits_media_code UNIQUE (code_statut)
);

CREATE TABLE mode_stockage_media (
    identifiant_mode_stockage_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_mode_stockage VARCHAR2(30 CHAR) NOT NULL,
    libelle_mode_stockage VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_mode_stockage_media_code UNIQUE (code_mode_stockage)
);

CREATE TABLE categorie_produit (
    identifiant_categorie_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_categorie VARCHAR2(30 CHAR) NOT NULL,
    libelle_categorie VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_categorie_produit_code UNIQUE (code_categorie)
);

CREATE TABLE statut_produit (
    identifiant_statut_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_produit_code UNIQUE (code_statut)
);

CREATE TABLE statut_commande (
    identifiant_statut_commande NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_commande_code UNIQUE (code_statut)
);

CREATE TABLE type_adhesion (
    identifiant_type_adhesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_adhesion VARCHAR2(30 CHAR) NOT NULL,
    libelle_type_adhesion VARCHAR2(100 CHAR) NOT NULL,
    montant_base NUMBER(10,2) DEFAULT 0 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_adhesion_code UNIQUE (code_type_adhesion),
    CONSTRAINT ck_type_adhesion_montant CHECK (montant_base >= 0)
);

CREATE TABLE statut_adhesion (
    identifiant_statut_adhesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_adhesion_code UNIQUE (code_statut)
);

CREATE TABLE type_activite (
    identifiant_type_activite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_activite VARCHAR2(40 CHAR) NOT NULL,
    libelle_type_activite VARCHAR2(120 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_activite_code UNIQUE (code_type_activite)
);

CREATE TABLE niveau_joueur (
    identifiant_niveau_joueur NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_niveau VARCHAR2(30 CHAR) NOT NULL,
    libelle_niveau VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_niveau_joueur_code UNIQUE (code_niveau),
    CONSTRAINT uq_niveau_joueur_ordre UNIQUE (ordre_affichage)
);

CREATE TABLE statut_inscription_session (
    identifiant_statut_inscription_session NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_inscription_session_code UNIQUE (code_statut)
);

CREATE TABLE statut_tournoi (
    identifiant_statut_tournoi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_tournoi_code UNIQUE (code_statut)
);

CREATE TABLE statut_inscription_tournoi (
    identifiant_statut_inscription_tournoi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_statut_inscription_tournoi_code UNIQUE (code_statut)
);

-- ============================================================
-- 2) COMPTES, PROFILS, CONSENTEMENTS
-- ============================================================

CREATE TABLE compte_membre (
    identifiant_compte_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adresse_courriel VARCHAR2(320 CHAR) NOT NULL,
    mot_de_passe_hache VARCHAR2(255 CHAR) NOT NULL,
    courriel_verifie_le TIMESTAMP WITH TIME ZONE NULL,
    identifiant_role_compte NUMBER NOT NULL,
    identifiant_statut_compte NUMBER NOT NULL,
    derniere_connexion_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_compte_membre_role
        FOREIGN KEY (identifiant_role_compte)
        REFERENCES role_compte (identifiant_role_compte),
    CONSTRAINT fk_compte_membre_statut
        FOREIGN KEY (identifiant_statut_compte)
        REFERENCES statut_compte (identifiant_statut_compte)
);

CREATE UNIQUE INDEX uq_compte_membre_email_lower
    ON compte_membre (LOWER(adresse_courriel));

CREATE TABLE profil_membre (
    identifiant_profil_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    prenom VARCHAR2(100 CHAR) NOT NULL,
    nom VARCHAR2(100 CHAR) NOT NULL,
    date_naissance DATE NULL,
    biographie CLOB NULL,
    pseudo_chess_com VARCHAR2(50 CHAR) NULL,
    fide_elo NUMBER(5) NULL,
    rapid_elo NUMBER(5) NULL,
    blitz_elo NUMBER(5) NULL,
    bullet_elo NUMBER(5) NULL,
    accepte_affichage_public_profil CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_profil_membre_compte UNIQUE (identifiant_compte_membre),
    CONSTRAINT ck_profil_public CHECK (accepte_affichage_public_profil IN ('Y', 'N')),
    CONSTRAINT ck_elo_fide CHECK (fide_elo IS NULL OR fide_elo BETWEEN 100 AND 3500),
    CONSTRAINT ck_elo_rapid CHECK (rapid_elo IS NULL OR rapid_elo BETWEEN 100 AND 3500),
    CONSTRAINT ck_elo_blitz CHECK (blitz_elo IS NULL OR blitz_elo BETWEEN 100 AND 3500),
    CONSTRAINT ck_elo_bullet CHECK (bullet_elo IS NULL OR bullet_elo BETWEEN 100 AND 3500),
    CONSTRAINT fk_profil_membre_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE consentement_cookie_visiteur (
    identifiant_consentement_cookie_visiteur NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jeton_consentement VARCHAR2(128 CHAR) NOT NULL,
    version_consentement VARCHAR2(40 CHAR) NOT NULL,
    accepte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    choix_theme VARCHAR2(10 CHAR) NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_cookie_visiteur_jeton UNIQUE (jeton_consentement)
);

CREATE TABLE consentement_membre (
    identifiant_consentement_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_type_consentement NUMBER NOT NULL,
    version_consentement VARCHAR2(40 CHAR) NOT NULL,
    accepte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_consentement_membre
        UNIQUE (identifiant_compte_membre, identifiant_type_consentement, version_consentement),
    CONSTRAINT fk_consentement_membre_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_consentement_membre_type
        FOREIGN KEY (identifiant_type_consentement)
        REFERENCES type_consentement (identifiant_type_consentement)
);

CREATE TABLE journal_connexion (
    identifiant_journal_connexion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    connecte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    succes CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    motif_echec VARCHAR2(200 CHAR) NULL,
    CONSTRAINT ck_journal_connexion_succes CHECK (succes IN ('Y', 'N')),
    CONSTRAINT fk_journal_connexion_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre)
);

-- ============================================================
-- 3) CONTENU EDITORIAL
-- ============================================================

CREATE TABLE article (
    identifiant_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_auteur NUMBER NOT NULL,
    identifiant_statut_publication NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    resume VARCHAR2(500 CHAR) NOT NULL,
    contenu CLOB NOT NULL,
    soumis_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    publie_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_auteur
        FOREIGN KEY (identifiant_compte_auteur)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_article_statut
        FOREIGN KEY (identifiant_statut_publication)
        REFERENCES statut_publication (identifiant_statut_publication)
);

CREATE INDEX idx_article_statut ON article (identifiant_statut_publication);
CREATE INDEX idx_article_soumis_le ON article (soumis_le);

CREATE TABLE revision_article (
    identifiant_revision_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    identifiant_compte_relecteur NUMBER NOT NULL,
    identifiant_type_decision_revision NUMBER NOT NULL,
    commentaire_revision CLOB NULL,
    decide_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_revision_article_article
        FOREIGN KEY (identifiant_article)
        REFERENCES article (identifiant_article),
    CONSTRAINT fk_revision_article_relecteur
        FOREIGN KEY (identifiant_compte_relecteur)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_revision_article_decision
        FOREIGN KEY (identifiant_type_decision_revision)
        REFERENCES type_decision_revision (identifiant_type_decision_revision)
);

-- ============================================================
-- 4) MEDIATHEQUE, DROITS ET LIAISONS
-- ============================================================

CREATE TABLE ressource_media (
    identifiant_ressource_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_type_media NUMBER NOT NULL,
    identifiant_mode_stockage_media NUMBER NOT NULL,
    identifiant_compte_depot NUMBER NULL,
    nom_fichier_original VARCHAR2(255 CHAR) NOT NULL,
    type_mime VARCHAR2(120 CHAR) NOT NULL,
    taille_octets NUMBER(19) NOT NULL,
    largeur_px NUMBER(10) NULL,
    hauteur_px NUMBER(10) NULL,
    duree_secondes NUMBER(10,3) NULL,
    texte_alternatif VARCHAR2(300 CHAR) NULL,
    date_capture DATE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_media_taille CHECK (taille_octets >= 0),
    CONSTRAINT fk_ressource_type_media
        FOREIGN KEY (identifiant_type_media)
        REFERENCES type_media (identifiant_type_media),
    CONSTRAINT fk_ressource_mode_stockage
        FOREIGN KEY (identifiant_mode_stockage_media)
        REFERENCES mode_stockage_media (identifiant_mode_stockage_media),
    CONSTRAINT fk_ressource_compte_depot
        FOREIGN KEY (identifiant_compte_depot)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE charge_binaire_media (
    identifiant_charge_binaire_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    charge_binaire BLOB NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_charge_binaire_ressource UNIQUE (identifiant_ressource_media),
    CONSTRAINT fk_charge_binaire_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE reference_externe_media (
    identifiant_reference_externe_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    fournisseur_stockage VARCHAR2(60 CHAR) NOT NULL,
    uri_stockage VARCHAR2(1000 CHAR) NOT NULL,
    empreinte_sha256 CHAR(64 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_reference_externe_ressource UNIQUE (identifiant_ressource_media),
    CONSTRAINT uq_reference_externe_uri UNIQUE (uri_stockage),
    CONSTRAINT uq_reference_externe_sha UNIQUE (empreinte_sha256),
    CONSTRAINT fk_reference_externe_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE autorisation_droits_media (
    identifiant_autorisation_droits_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_statut_droits_media NUMBER NOT NULL,
    nom_titulaire_droits VARCHAR2(200 CHAR) NOT NULL,
    reference_consentement VARCHAR2(200 CHAR) NULL,
    perimetre_autorisation VARCHAR2(200 CHAR) NOT NULL,
    autorise_le TIMESTAMP WITH TIME ZONE NOT NULL,
    expire_le TIMESTAMP WITH TIME ZONE NULL,
    commentaire_revision VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_droits_media_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_droits_media_statut
        FOREIGN KEY (identifiant_statut_droits_media)
        REFERENCES statut_droits_media (identifiant_statut_droits_media)
);

CREATE TABLE album_media (
    identifiant_album_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_createur NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    description CLOB NULL,
    est_public CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_album_public CHECK (est_public IN ('Y', 'N')),
    CONSTRAINT fk_album_createur
        FOREIGN KEY (identifiant_compte_createur)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE element_album_media (
    identifiant_element_album_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_album_media NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    legende VARCHAR2(300 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_element_album UNIQUE (identifiant_album_media, identifiant_ressource_media),
    CONSTRAINT fk_element_album
        FOREIGN KEY (identifiant_album_media)
        REFERENCES album_media (identifiant_album_media),
    CONSTRAINT fk_element_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE media_article (
    identifiant_media_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_type_usage_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_article UNIQUE (
        identifiant_article,
        identifiant_ressource_media,
        identifiant_type_usage_media
    ),
    CONSTRAINT fk_media_article_article
        FOREIGN KEY (identifiant_article)
        REFERENCES article (identifiant_article),
    CONSTRAINT fk_media_article_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_media_article_usage
        FOREIGN KEY (identifiant_type_usage_media)
        REFERENCES type_usage_media (identifiant_type_usage_media)
);

-- ============================================================
-- 5) BOUTIQUE ET COMMANDES
-- ============================================================

CREATE TABLE produit (
    identifiant_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_categorie_produit NUMBER NOT NULL,
    identifiant_statut_produit NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    reference_stock VARCHAR2(80 CHAR) NULL,
    description_courte VARCHAR2(500 CHAR) NOT NULL,
    description_longue CLOB NULL,
    quantite_stock NUMBER(10) DEFAULT 0 NOT NULL,
    disponible_a_partir_de TIMESTAMP WITH TIME ZONE NULL,
    disponible_jusqua TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_produit_slug UNIQUE (slug),
    CONSTRAINT uq_produit_reference_stock UNIQUE (reference_stock),
    CONSTRAINT ck_produit_stock CHECK (quantite_stock >= 0),
    CONSTRAINT fk_produit_categorie
        FOREIGN KEY (identifiant_categorie_produit)
        REFERENCES categorie_produit (identifiant_categorie_produit),
    CONSTRAINT fk_produit_statut
        FOREIGN KEY (identifiant_statut_produit)
        REFERENCES statut_produit (identifiant_statut_produit)
);

CREATE TABLE prix_produit (
    identifiant_prix_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_produit NUMBER NOT NULL,
    code_devise CHAR(3 CHAR) NOT NULL,
    montant NUMBER(10,2) NOT NULL,
    applicable_a_partir_de TIMESTAMP WITH TIME ZONE NOT NULL,
    applicable_jusqua TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_prix_produit UNIQUE (
        identifiant_produit,
        code_devise,
        applicable_a_partir_de
    ),
    CONSTRAINT ck_prix_produit_montant CHECK (montant >= 0),
    CONSTRAINT fk_prix_produit
        FOREIGN KEY (identifiant_produit)
        REFERENCES produit (identifiant_produit)
);

CREATE TABLE media_produit (
    identifiant_media_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_produit NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_type_usage_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_produit UNIQUE (
        identifiant_produit,
        identifiant_ressource_media,
        identifiant_type_usage_media
    ),
    CONSTRAINT fk_media_produit_produit
        FOREIGN KEY (identifiant_produit)
        REFERENCES produit (identifiant_produit),
    CONSTRAINT fk_media_produit_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_media_produit_usage
        FOREIGN KEY (identifiant_type_usage_media)
        REFERENCES type_usage_media (identifiant_type_usage_media)
);

CREATE TABLE commande_client (
    identifiant_commande_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NULL,
    identifiant_statut_commande NUMBER NOT NULL,
    reference_commande VARCHAR2(50 CHAR) NOT NULL,
    nom_facturation VARCHAR2(200 CHAR) NOT NULL,
    courriel_facturation VARCHAR2(320 CHAR) NOT NULL,
    code_devise CHAR(3 CHAR) NOT NULL,
    commandee_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    payee_le TIMESTAMP WITH TIME ZONE NULL,
    annulee_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_commande_reference UNIQUE (reference_commande),
    CONSTRAINT fk_commande_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_commande_statut
        FOREIGN KEY (identifiant_statut_commande)
        REFERENCES statut_commande (identifiant_statut_commande)
);

CREATE TABLE ligne_commande_client (
    identifiant_ligne_commande_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_commande_client NUMBER NOT NULL,
    identifiant_produit NUMBER NOT NULL,
    quantite NUMBER(10) NOT NULL,
    prix_unitaire NUMBER(10,2) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_ligne_commande_quantite CHECK (quantite > 0),
    CONSTRAINT ck_ligne_commande_prix CHECK (prix_unitaire >= 0),
    CONSTRAINT fk_ligne_commande
        FOREIGN KEY (identifiant_commande_client)
        REFERENCES commande_client (identifiant_commande_client),
    CONSTRAINT fk_ligne_produit
        FOREIGN KEY (identifiant_produit)
        REFERENCES produit (identifiant_produit)
);

-- ============================================================
-- 6) VRAI FONCTIONNEMENT CLUB (ADHESIONS, ACTIVITES, TOURNOIS)
-- ============================================================

CREATE TABLE saison_club (
    identifiant_saison_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_saison VARCHAR2(20 CHAR) NOT NULL,
    libelle_saison VARCHAR2(120 CHAR) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    est_saison_active CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_saison_code UNIQUE (code_saison),
    CONSTRAINT ck_saison_active CHECK (est_saison_active IN ('Y', 'N')),
    CONSTRAINT ck_saison_dates CHECK (date_fin >= date_debut)
);

CREATE TABLE adhesion_membre (
    identifiant_adhesion_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_saison_club NUMBER NOT NULL,
    identifiant_type_adhesion NUMBER NOT NULL,
    identifiant_statut_adhesion NUMBER NOT NULL,
    montant_attendu NUMBER(10,2) NOT NULL,
    montant_paye NUMBER(10,2) DEFAULT 0 NOT NULL,
    date_demande DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    date_validation DATE NULL,
    date_expiration DATE NULL,
    commentaire_admin VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_adhesion_membre_saison UNIQUE (
        identifiant_compte_membre,
        identifiant_saison_club
    ),
    CONSTRAINT ck_adhesion_montants CHECK (
        montant_attendu >= 0 AND montant_paye >= 0 AND montant_paye <= montant_attendu
    ),
    CONSTRAINT fk_adhesion_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_adhesion_saison
        FOREIGN KEY (identifiant_saison_club)
        REFERENCES saison_club (identifiant_saison_club),
    CONSTRAINT fk_adhesion_type
        FOREIGN KEY (identifiant_type_adhesion)
        REFERENCES type_adhesion (identifiant_type_adhesion),
    CONSTRAINT fk_adhesion_statut
        FOREIGN KEY (identifiant_statut_adhesion)
        REFERENCES statut_adhesion (identifiant_statut_adhesion)
);

CREATE INDEX idx_adhesion_statut ON adhesion_membre (identifiant_statut_adhesion);

CREATE TABLE paiement_adhesion (
    identifiant_paiement_adhesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_adhesion_membre NUMBER NOT NULL,
    reference_paiement VARCHAR2(80 CHAR) NOT NULL,
    montant NUMBER(10,2) NOT NULL,
    devise CHAR(3 CHAR) DEFAULT 'EUR' NOT NULL,
    mode_paiement VARCHAR2(30 CHAR) NOT NULL,
    statut_paiement VARCHAR2(30 CHAR) NOT NULL,
    paye_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_paiement_adhesion_reference UNIQUE (reference_paiement),
    CONSTRAINT ck_paiement_adhesion_montant CHECK (montant > 0),
    CONSTRAINT fk_paiement_adhesion
        FOREIGN KEY (identifiant_adhesion_membre)
        REFERENCES adhesion_membre (identifiant_adhesion_membre)
);

CREATE TABLE activite_club (
    identifiant_activite_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_type_activite NUMBER NOT NULL,
    identifiant_niveau_min NUMBER NULL,
    identifiant_niveau_max NUMBER NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    description_courte VARCHAR2(500 CHAR) NOT NULL,
    description_longue CLOB NULL,
    duree_minutes NUMBER(6) NULL,
    est_visible_publiquement CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_activite_slug UNIQUE (slug),
    CONSTRAINT ck_activite_public CHECK (est_visible_publiquement IN ('Y', 'N')),
    CONSTRAINT ck_activite_duree CHECK (duree_minutes IS NULL OR duree_minutes > 0),
    CONSTRAINT fk_activite_type
        FOREIGN KEY (identifiant_type_activite)
        REFERENCES type_activite (identifiant_type_activite),
    CONSTRAINT fk_activite_niveau_min
        FOREIGN KEY (identifiant_niveau_min)
        REFERENCES niveau_joueur (identifiant_niveau_joueur),
    CONSTRAINT fk_activite_niveau_max
        FOREIGN KEY (identifiant_niveau_max)
        REFERENCES niveau_joueur (identifiant_niveau_joueur)
);

CREATE TABLE session_activite (
    identifiant_session_activite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_activite_club NUMBER NOT NULL,
    identifiant_saison_club NUMBER NULL,
    identifiant_compte_encadrant NUMBER NULL,
    lieu VARCHAR2(200 CHAR) NULL,
    date_debut TIMESTAMP WITH TIME ZONE NOT NULL,
    date_fin TIMESTAMP WITH TIME ZONE NOT NULL,
    places_max NUMBER(6) NULL,
    notes_logistiques VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_session_dates CHECK (date_fin > date_debut),
    CONSTRAINT ck_session_places CHECK (places_max IS NULL OR places_max > 0),
    CONSTRAINT fk_session_activite
        FOREIGN KEY (identifiant_activite_club)
        REFERENCES activite_club (identifiant_activite_club),
    CONSTRAINT fk_session_saison
        FOREIGN KEY (identifiant_saison_club)
        REFERENCES saison_club (identifiant_saison_club),
    CONSTRAINT fk_session_encadrant
        FOREIGN KEY (identifiant_compte_encadrant)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE INDEX idx_session_activite_date_debut ON session_activite (date_debut);

CREATE TABLE inscription_session_activite (
    identifiant_inscription_session_activite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_session_activite NUMBER NOT NULL,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_statut_inscription_session NUMBER NOT NULL,
    inscrit_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    presence_confirmee_le TIMESTAMP WITH TIME ZONE NULL,
    commentaire VARCHAR2(300 CHAR) NULL,
    CONSTRAINT uq_inscription_session UNIQUE (
        identifiant_session_activite,
        identifiant_compte_membre
    ),
    CONSTRAINT fk_inscription_session
        FOREIGN KEY (identifiant_session_activite)
        REFERENCES session_activite (identifiant_session_activite),
    CONSTRAINT fk_inscription_session_membre
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_inscription_session_statut
        FOREIGN KEY (identifiant_statut_inscription_session)
        REFERENCES statut_inscription_session (identifiant_statut_inscription_session)
);

CREATE TABLE tournoi_club (
    identifiant_tournoi_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_saison_club NUMBER NULL,
    identifiant_statut_tournoi NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    format_tournoi VARCHAR2(40 CHAR) NOT NULL,
    cadence VARCHAR2(40 CHAR) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    lieu VARCHAR2(200 CHAR) NULL,
    droit_inscription NUMBER(10,2) DEFAULT 0 NOT NULL,
    description CLOB NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_tournoi_slug UNIQUE (slug),
    CONSTRAINT ck_tournoi_dates CHECK (date_fin >= date_debut),
    CONSTRAINT ck_tournoi_droit CHECK (droit_inscription >= 0),
    CONSTRAINT fk_tournoi_saison
        FOREIGN KEY (identifiant_saison_club)
        REFERENCES saison_club (identifiant_saison_club),
    CONSTRAINT fk_tournoi_statut
        FOREIGN KEY (identifiant_statut_tournoi)
        REFERENCES statut_tournoi (identifiant_statut_tournoi)
);

CREATE TABLE inscription_tournoi_club (
    identifiant_inscription_tournoi_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_tournoi_club NUMBER NOT NULL,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_statut_inscription_tournoi NUMBER NOT NULL,
    elo_snapshot NUMBER(5) NULL,
    score_final NUMBER(5,2) NULL,
    rang_final NUMBER(6) NULL,
    inscrit_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    commentaire VARCHAR2(300 CHAR) NULL,
    CONSTRAINT uq_inscription_tournoi UNIQUE (
        identifiant_tournoi_club,
        identifiant_compte_membre
    ),
    CONSTRAINT ck_inscription_tournoi_elo CHECK (elo_snapshot IS NULL OR elo_snapshot BETWEEN 100 AND 3500),
    CONSTRAINT fk_inscription_tournoi
        FOREIGN KEY (identifiant_tournoi_club)
        REFERENCES tournoi_club (identifiant_tournoi_club),
    CONSTRAINT fk_inscription_tournoi_membre
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_inscription_tournoi_statut
        FOREIGN KEY (identifiant_statut_inscription_tournoi)
        REFERENCES statut_inscription_tournoi (identifiant_statut_inscription_tournoi)
);

CREATE TABLE rencontre_interclub (
    identifiant_rencontre_interclub NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_saison_club NUMBER NOT NULL,
    nom_equipe_locale VARCHAR2(150 CHAR) NOT NULL,
    nom_equipe_adverse VARCHAR2(150 CHAR) NOT NULL,
    competition VARCHAR2(120 CHAR) NOT NULL,
    date_rencontre TIMESTAMP WITH TIME ZONE NOT NULL,
    est_domicile CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    score_local NUMBER(4,1) NULL,
    score_adverse NUMBER(4,1) NULL,
    commentaire VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_rencontre_domicile CHECK (est_domicile IN ('Y', 'N')),
    CONSTRAINT fk_rencontre_saison
        FOREIGN KEY (identifiant_saison_club)
        REFERENCES saison_club (identifiant_saison_club)
);

CREATE TABLE participation_rencontre_interclub (
    identifiant_participation_rencontre_interclub NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_rencontre_interclub NUMBER NOT NULL,
    identifiant_compte_membre NUMBER NOT NULL,
    numero_echiquier NUMBER(3) NOT NULL,
    couleur VARCHAR2(5 CHAR) NULL,
    resultat VARCHAR2(15 CHAR) NULL,
    CONSTRAINT uq_participation_rencontre UNIQUE (
        identifiant_rencontre_interclub,
        identifiant_compte_membre
    ),
    CONSTRAINT uq_participation_rencontre_echiquier UNIQUE (
        identifiant_rencontre_interclub,
        numero_echiquier
    ),
    CONSTRAINT ck_participation_couleur CHECK (couleur IS NULL OR couleur IN ('blanc', 'noir')),
    CONSTRAINT ck_participation_resultat CHECK (
        resultat IS NULL OR resultat IN ('gagne', 'nul', 'perdu', 'forfait')
    ),
    CONSTRAINT fk_participation_rencontre
        FOREIGN KEY (identifiant_rencontre_interclub)
        REFERENCES rencontre_interclub (identifiant_rencontre_interclub),
    CONSTRAINT fk_participation_membre
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre)
);

-- ============================================================
-- 7) CONTACT SITE
-- ============================================================

CREATE TABLE message_contact (
    identifiant_message_contact NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_expediteur VARCHAR2(150 CHAR) NOT NULL,
    courriel_expediteur VARCHAR2(320 CHAR) NOT NULL,
    sujet VARCHAR2(200 CHAR) NOT NULL,
    message CLOB NOT NULL,
    traite CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    traite_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_message_contact_traite CHECK (traite IN ('Y', 'N'))
);

CREATE INDEX idx_message_contact_traite ON message_contact (traite, cree_le);

-- ============================================================
-- 8) DONNEES DE REFERENCE (fusion de 002_reference-data.sql)
-- ============================================================

INSERT INTO role_compte (code_role, libelle_role) VALUES ('membre', 'Membre');
INSERT INTO role_compte (code_role, libelle_role) VALUES ('redacteur', 'Redacteur');
INSERT INTO role_compte (code_role, libelle_role) VALUES ('coach', 'Coach');
INSERT INTO role_compte (code_role, libelle_role) VALUES ('tresorier', 'Tresorier');
INSERT INTO role_compte (code_role, libelle_role) VALUES ('admin', 'Administrateur');

INSERT INTO statut_compte (code_statut, libelle_statut) VALUES ('en_attente', 'En attente');
INSERT INTO statut_compte (code_statut, libelle_statut) VALUES ('actif', 'Actif');
INSERT INTO statut_compte (code_statut, libelle_statut) VALUES ('suspendu', 'Suspendu');
INSERT INTO statut_compte (code_statut, libelle_statut) VALUES ('supprime', 'Supprime');

INSERT INTO statut_publication (code_statut, libelle_statut) VALUES ('brouillon', 'Brouillon');
INSERT INTO statut_publication (code_statut, libelle_statut) VALUES ('en_attente_validation', 'En attente de validation');
INSERT INTO statut_publication (code_statut, libelle_statut) VALUES ('approuve', 'Approuve');
INSERT INTO statut_publication (code_statut, libelle_statut) VALUES ('refuse', 'Refuse');
INSERT INTO statut_publication (code_statut, libelle_statut) VALUES ('publie', 'Publie');
INSERT INTO statut_publication (code_statut, libelle_statut) VALUES ('archive', 'Archive');

INSERT INTO type_decision_revision (code_decision, libelle_decision) VALUES ('demander_modifications', 'Demander modifications');
INSERT INTO type_decision_revision (code_decision, libelle_decision) VALUES ('approuver', 'Approuver');
INSERT INTO type_decision_revision (code_decision, libelle_decision) VALUES ('refuser', 'Refuser');

INSERT INTO type_consentement (code_consentement, libelle_consentement, base_legale, duree_conservation_mois, est_obligatoire)
VALUES ('politique_confidentialite', 'Politique de confidentialite', 'Obligation information', 24, 'Y');
INSERT INTO type_consentement (code_consentement, libelle_consentement, base_legale, duree_conservation_mois, est_obligatoire)
VALUES ('conditions_utilisation', 'Conditions utilisation', 'Interet legitime', 24, 'Y');
INSERT INTO type_consentement (code_consentement, libelle_consentement, base_legale, duree_conservation_mois, est_obligatoire)
VALUES ('cookies_essentiels', 'Cookies essentiels', 'Fonctionnement service', 24, 'Y');
INSERT INTO type_consentement (code_consentement, libelle_consentement, base_legale, duree_conservation_mois, est_obligatoire)
VALUES ('preference_theme', 'Preference theme', 'Preference utilisateur', 24, 'N');
INSERT INTO type_consentement (code_consentement, libelle_consentement, base_legale, duree_conservation_mois, est_obligatoire)
VALUES ('publication_media', 'Autorisation diffusion image video', 'Consentement', 36, 'N');

INSERT INTO type_media (code_type_media, libelle_type_media) VALUES ('image', 'Image');
INSERT INTO type_media (code_type_media, libelle_type_media) VALUES ('video', 'Video');

INSERT INTO type_usage_media (code_usage, libelle_usage) VALUES ('couverture_article', 'Illustration principale article');
INSERT INTO type_usage_media (code_usage, libelle_usage) VALUES ('galerie_article', 'Galerie article');
INSERT INTO type_usage_media (code_usage, libelle_usage) VALUES ('galerie_album', 'Galerie mediatheque');
INSERT INTO type_usage_media (code_usage, libelle_usage) VALUES ('produit_principal', 'Visuel principal produit');
INSERT INTO type_usage_media (code_usage, libelle_usage) VALUES ('galerie_produit', 'Galerie produit');

INSERT INTO statut_droits_media (code_statut, libelle_statut) VALUES ('en_attente', 'En attente verification');
INSERT INTO statut_droits_media (code_statut, libelle_statut) VALUES ('accorde', 'Droits accordes');
INSERT INTO statut_droits_media (code_statut, libelle_statut) VALUES ('expire', 'Droits expires');
INSERT INTO statut_droits_media (code_statut, libelle_statut) VALUES ('revoque', 'Droits revoques');

INSERT INTO mode_stockage_media (code_mode_stockage, libelle_mode_stockage) VALUES ('blob_base', 'Stockage Oracle');
INSERT INTO mode_stockage_media (code_mode_stockage, libelle_mode_stockage) VALUES ('uri_externe', 'Stockage externe reference');

INSERT INTO categorie_produit (code_categorie, libelle_categorie) VALUES ('textile', 'Textile');
INSERT INTO categorie_produit (code_categorie, libelle_categorie) VALUES ('accessoire', 'Accessoire');
INSERT INTO categorie_produit (code_categorie, libelle_categorie) VALUES ('materiel', 'Materiel');
INSERT INTO categorie_produit (code_categorie, libelle_categorie) VALUES ('autre', 'Autre');

INSERT INTO statut_produit (code_statut, libelle_statut) VALUES ('brouillon', 'Brouillon');
INSERT INTO statut_produit (code_statut, libelle_statut) VALUES ('actif', 'Actif');
INSERT INTO statut_produit (code_statut, libelle_statut) VALUES ('indisponible', 'Indisponible');
INSERT INTO statut_produit (code_statut, libelle_statut) VALUES ('expire', 'Expire');
INSERT INTO statut_produit (code_statut, libelle_statut) VALUES ('archive', 'Archive');

INSERT INTO statut_commande (code_statut, libelle_statut) VALUES ('en_attente', 'En attente');
INSERT INTO statut_commande (code_statut, libelle_statut) VALUES ('paye', 'Paye');
INSERT INTO statut_commande (code_statut, libelle_statut) VALUES ('annule', 'Annule');
INSERT INTO statut_commande (code_statut, libelle_statut) VALUES ('rembourse', 'Rembourse');

INSERT INTO type_adhesion (code_type_adhesion, libelle_type_adhesion, montant_base)
VALUES ('jeune', 'Adhesion jeune', 90);
INSERT INTO type_adhesion (code_type_adhesion, libelle_type_adhesion, montant_base)
VALUES ('adulte', 'Adhesion adulte', 140);
INSERT INTO type_adhesion (code_type_adhesion, libelle_type_adhesion, montant_base)
VALUES ('etudiant', 'Adhesion etudiant', 110);
INSERT INTO type_adhesion (code_type_adhesion, libelle_type_adhesion, montant_base)
VALUES ('benevole', 'Adhesion benevole', 0);

INSERT INTO statut_adhesion (code_statut, libelle_statut) VALUES ('brouillon', 'Brouillon');
INSERT INTO statut_adhesion (code_statut, libelle_statut) VALUES ('en_attente_paiement', 'En attente paiement');
INSERT INTO statut_adhesion (code_statut, libelle_statut) VALUES ('active', 'Active');
INSERT INTO statut_adhesion (code_statut, libelle_statut) VALUES ('expiree', 'Expiree');
INSERT INTO statut_adhesion (code_statut, libelle_statut) VALUES ('annulee', 'Annulee');

INSERT INTO type_activite (code_type_activite, libelle_type_activite) VALUES ('cours', 'Cours');
INSERT INTO type_activite (code_type_activite, libelle_type_activite) VALUES ('entrainement', 'Entrainement');
INSERT INTO type_activite (code_type_activite, libelle_type_activite) VALUES ('analyse', 'Analyse de parties');
INSERT INTO type_activite (code_type_activite, libelle_type_activite) VALUES ('competition', 'Competition');
INSERT INTO type_activite (code_type_activite, libelle_type_activite) VALUES ('animation', 'Animation club');

INSERT INTO niveau_joueur (code_niveau, libelle_niveau, ordre_affichage) VALUES ('debutant', 'Debutant', 10);
INSERT INTO niveau_joueur (code_niveau, libelle_niveau, ordre_affichage) VALUES ('intermediaire', 'Intermediaire', 20);
INSERT INTO niveau_joueur (code_niveau, libelle_niveau, ordre_affichage) VALUES ('avance', 'Avance', 30);
INSERT INTO niveau_joueur (code_niveau, libelle_niveau, ordre_affichage) VALUES ('expert', 'Expert', 40);

INSERT INTO statut_inscription_session (code_statut, libelle_statut) VALUES ('inscrit', 'Inscrit');
INSERT INTO statut_inscription_session (code_statut, libelle_statut) VALUES ('liste_attente', 'Liste attente');
INSERT INTO statut_inscription_session (code_statut, libelle_statut) VALUES ('present', 'Present');
INSERT INTO statut_inscription_session (code_statut, libelle_statut) VALUES ('absent', 'Absent');
INSERT INTO statut_inscription_session (code_statut, libelle_statut) VALUES ('annule', 'Annule');

INSERT INTO statut_tournoi (code_statut, libelle_statut) VALUES ('brouillon', 'Brouillon');
INSERT INTO statut_tournoi (code_statut, libelle_statut) VALUES ('ouvert_inscription', 'Ouvert inscription');
INSERT INTO statut_tournoi (code_statut, libelle_statut) VALUES ('en_cours', 'En cours');
INSERT INTO statut_tournoi (code_statut, libelle_statut) VALUES ('termine', 'Termine');
INSERT INTO statut_tournoi (code_statut, libelle_statut) VALUES ('annule', 'Annule');

INSERT INTO statut_inscription_tournoi (code_statut, libelle_statut) VALUES ('inscrit', 'Inscrit');
INSERT INTO statut_inscription_tournoi (code_statut, libelle_statut) VALUES ('confirme', 'Confirme');
INSERT INTO statut_inscription_tournoi (code_statut, libelle_statut) VALUES ('retire', 'Retire');
INSERT INTO statut_inscription_tournoi (code_statut, libelle_statut) VALUES ('forfait', 'Forfait');

COMMIT;

-- ============================================================
-- 9) TRIGGERS DE NORMALISATION ET HORODATAGE
-- ============================================================

CREATE OR REPLACE TRIGGER trg_compte_membre_biu
BEFORE INSERT OR UPDATE ON compte_membre
FOR EACH ROW
BEGIN
    :NEW.adresse_courriel := LOWER(TRIM(:NEW.adresse_courriel));

    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_profil_membre_biu
BEFORE INSERT OR UPDATE ON profil_membre
FOR EACH ROW
BEGIN
    :NEW.pseudo_chess_com := LOWER(TRIM(:NEW.pseudo_chess_com));

    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_article_biu
BEFORE INSERT OR UPDATE ON article
FOR EACH ROW
DECLARE
    v_publie_status_id statut_publication.identifiant_statut_publication%TYPE;
BEGIN
    SELECT identifiant_statut_publication
      INTO v_publie_status_id
      FROM statut_publication
     WHERE code_statut = 'publie';

    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
        :NEW.soumis_le := COALESCE(:NEW.soumis_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;

    IF :NEW.identifiant_statut_publication = v_publie_status_id AND :NEW.publie_le IS NULL THEN
        :NEW.publie_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_ressource_media_biu
BEFORE INSERT OR UPDATE ON ressource_media
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_reference_externe_media_biu
BEFORE INSERT OR UPDATE ON reference_externe_media
FOR EACH ROW
BEGIN
    :NEW.fournisseur_stockage := TRIM(:NEW.fournisseur_stockage);
    :NEW.uri_stockage := TRIM(:NEW.uri_stockage);
    :NEW.empreinte_sha256 := LOWER(TRIM(:NEW.empreinte_sha256));

    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_autorisation_droits_media_biu
BEFORE INSERT OR UPDATE ON autorisation_droits_media
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_album_media_biu
BEFORE INSERT OR UPDATE ON album_media
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_produit_biu
BEFORE INSERT OR UPDATE ON produit
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_commande_client_biu
BEFORE INSERT OR UPDATE ON commande_client
FOR EACH ROW
BEGIN
    :NEW.courriel_facturation := LOWER(TRIM(:NEW.courriel_facturation));

    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
        :NEW.commandee_le := COALESCE(:NEW.commandee_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_adhesion_membre_biu
BEFORE INSERT OR UPDATE ON adhesion_membre
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_paiement_adhesion_biu
BEFORE INSERT OR UPDATE ON paiement_adhesion
FOR EACH ROW
BEGIN
    :NEW.reference_paiement := UPPER(TRIM(:NEW.reference_paiement));
    :NEW.mode_paiement := LOWER(TRIM(:NEW.mode_paiement));
    :NEW.statut_paiement := LOWER(TRIM(:NEW.statut_paiement));

    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_activite_club_biu
BEFORE INSERT OR UPDATE ON activite_club
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_session_activite_biu
BEFORE INSERT OR UPDATE ON session_activite
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_tournoi_club_biu
BEFORE INSERT OR UPDATE ON tournoi_club
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_rencontre_interclub_biu
BEFORE INSERT OR UPDATE ON rencontre_interclub
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.cree_le := COALESCE(:NEW.cree_le, SYSTIMESTAMP);
        :NEW.mis_a_jour_le := COALESCE(:NEW.mis_a_jour_le, SYSTIMESTAMP);
    ELSE
        :NEW.mis_a_jour_le := SYSTIMESTAMP;
    END IF;
END;
/

-- Mise a jour automatique du montant paye sur l'adhesion
CREATE OR REPLACE TRIGGER trg_paiement_adhesion_aiud
AFTER INSERT OR UPDATE OR DELETE ON paiement_adhesion
FOR EACH ROW
BEGIN
    UPDATE adhesion_membre am
       SET montant_paye = (
            SELECT COALESCE(SUM(pa.montant), 0)
              FROM paiement_adhesion pa
             WHERE pa.identifiant_adhesion_membre = am.identifiant_adhesion_membre
               AND pa.statut_paiement IN ('paye', 'valide')
       ),
           mis_a_jour_le = SYSTIMESTAMP
     WHERE am.identifiant_adhesion_membre = COALESCE(:NEW.identifiant_adhesion_membre, :OLD.identifiant_adhesion_membre);
END;
/

-- ============================================================
-- 10) VUES METIER
-- ============================================================

CREATE OR REPLACE VIEW vw_ressources_media_pretes_publication AS
SELECT rm.identifiant_ressource_media,
       rm.identifiant_type_media,
       rm.identifiant_mode_stockage_media,
       rm.identifiant_compte_depot,
       rm.nom_fichier_original,
       rm.type_mime,
       rm.taille_octets,
       rm.largeur_px,
       rm.hauteur_px,
       rm.duree_secondes,
       rm.texte_alternatif,
       rm.date_capture,
       rm.cree_le,
       rm.mis_a_jour_le
  FROM ressource_media rm
 WHERE EXISTS (
        SELECT 1
          FROM autorisation_droits_media adm
          JOIN statut_droits_media sdm
            ON sdm.identifiant_statut_droits_media = adm.identifiant_statut_droits_media
         WHERE adm.identifiant_ressource_media = rm.identifiant_ressource_media
           AND sdm.code_statut = 'accorde'
           AND (adm.expire_le IS NULL OR adm.expire_le >= SYSTIMESTAMP)
      );
/

CREATE OR REPLACE VIEW vw_totaux_commande_client AS
SELECT lcc.identifiant_commande_client,
       SUM(lcc.quantite * lcc.prix_unitaire) AS total_montant
  FROM ligne_commande_client lcc
 GROUP BY lcc.identifiant_commande_client;
/

CREATE OR REPLACE VIEW vw_adhesions_actives AS
SELECT am.identifiant_adhesion_membre,
       am.identifiant_compte_membre,
       am.identifiant_saison_club,
       am.montant_attendu,
       am.montant_paye,
       sa.code_statut,
       sc.code_saison,
       sc.libelle_saison,
       sc.date_debut,
       sc.date_fin
  FROM adhesion_membre am
  JOIN statut_adhesion sa
    ON sa.identifiant_statut_adhesion = am.identifiant_statut_adhesion
  JOIN saison_club sc
    ON sc.identifiant_saison_club = am.identifiant_saison_club
 WHERE sa.code_statut = 'active';
/

CREATE OR REPLACE VIEW vw_calendrier_activites_public AS
SELECT sa.identifiant_session_activite,
       ac.titre AS activite_titre,
       ta.code_type_activite,
       ta.libelle_type_activite,
       sa.date_debut,
       sa.date_fin,
       sa.lieu,
       sa.places_max
  FROM session_activite sa
  JOIN activite_club ac
    ON ac.identifiant_activite_club = sa.identifiant_activite_club
  JOIN type_activite ta
    ON ta.identifiant_type_activite = ac.identifiant_type_activite
 WHERE ac.est_visible_publiquement = 'Y'
   AND sa.date_fin >= SYSTIMESTAMP;
/

-- ============================================================
-- 11) PACKAGE DE MAINTENANCE
-- ============================================================

CREATE OR REPLACE PACKAGE pkg_maintenance_site AS
    PROCEDURE cloturer_droits_media_expires;
    PROCEDURE archiver_articles_en_attente_anciens(p_seuil_jours NUMBER DEFAULT 180);
    PROCEDURE expirer_catalogue_boutique;
    PROCEDURE purger_anciens_consentements_visiteurs(p_mois_conservation NUMBER DEFAULT 24);
    PROCEDURE cloturer_adhesions_expirees;
    PROCEDURE marquer_tournois_termines;
    PROCEDURE lancer_maintenance_quotidienne;
END pkg_maintenance_site;
/

CREATE OR REPLACE PACKAGE BODY pkg_maintenance_site AS
    PROCEDURE cloturer_droits_media_expires IS
        v_statut_expire statut_droits_media.identifiant_statut_droits_media%TYPE;
        v_statut_accorde statut_droits_media.identifiant_statut_droits_media%TYPE;
    BEGIN
        SELECT identifiant_statut_droits_media
          INTO v_statut_expire
          FROM statut_droits_media
         WHERE code_statut = 'expire';

        SELECT identifiant_statut_droits_media
          INTO v_statut_accorde
          FROM statut_droits_media
         WHERE code_statut = 'accorde';

        UPDATE autorisation_droits_media
           SET identifiant_statut_droits_media = v_statut_expire,
               mis_a_jour_le = SYSTIMESTAMP
         WHERE identifiant_statut_droits_media = v_statut_accorde
           AND expire_le IS NOT NULL
           AND expire_le < SYSTIMESTAMP;
    END cloturer_droits_media_expires;

    PROCEDURE archiver_articles_en_attente_anciens(p_seuil_jours NUMBER DEFAULT 180) IS
        v_statut_attente statut_publication.identifiant_statut_publication%TYPE;
        v_statut_archive statut_publication.identifiant_statut_publication%TYPE;
    BEGIN
        SELECT identifiant_statut_publication
          INTO v_statut_attente
          FROM statut_publication
         WHERE code_statut = 'en_attente_validation';

        SELECT identifiant_statut_publication
          INTO v_statut_archive
          FROM statut_publication
         WHERE code_statut = 'archive';

        UPDATE article
           SET identifiant_statut_publication = v_statut_archive,
               mis_a_jour_le = SYSTIMESTAMP
         WHERE identifiant_statut_publication = v_statut_attente
           AND soumis_le < SYSTIMESTAMP - NUMTODSINTERVAL(p_seuil_jours, 'DAY');
    END archiver_articles_en_attente_anciens;

    PROCEDURE expirer_catalogue_boutique IS
        v_statut_actif statut_produit.identifiant_statut_produit%TYPE;
        v_statut_expire statut_produit.identifiant_statut_produit%TYPE;
    BEGIN
        SELECT identifiant_statut_produit
          INTO v_statut_actif
          FROM statut_produit
         WHERE code_statut = 'actif';

        SELECT identifiant_statut_produit
          INTO v_statut_expire
          FROM statut_produit
         WHERE code_statut = 'expire';

        UPDATE produit
           SET identifiant_statut_produit = v_statut_expire,
               mis_a_jour_le = SYSTIMESTAMP
         WHERE identifiant_statut_produit = v_statut_actif
           AND disponible_jusqua IS NOT NULL
           AND disponible_jusqua < SYSTIMESTAMP;
    END expirer_catalogue_boutique;

    PROCEDURE purger_anciens_consentements_visiteurs(p_mois_conservation NUMBER DEFAULT 24) IS
    BEGIN
        DELETE FROM consentement_cookie_visiteur
         WHERE accepte_le < (SYSTIMESTAMP - NUMTOYMINTERVAL(p_mois_conservation, 'MONTH'));
    END purger_anciens_consentements_visiteurs;

    PROCEDURE cloturer_adhesions_expirees IS
        v_statut_active statut_adhesion.identifiant_statut_adhesion%TYPE;
        v_statut_expiree statut_adhesion.identifiant_statut_adhesion%TYPE;
    BEGIN
        SELECT identifiant_statut_adhesion
          INTO v_statut_active
          FROM statut_adhesion
         WHERE code_statut = 'active';

        SELECT identifiant_statut_adhesion
          INTO v_statut_expiree
          FROM statut_adhesion
         WHERE code_statut = 'expiree';

        UPDATE adhesion_membre
           SET identifiant_statut_adhesion = v_statut_expiree,
               mis_a_jour_le = SYSTIMESTAMP
         WHERE identifiant_statut_adhesion = v_statut_active
           AND date_expiration IS NOT NULL
           AND date_expiration < TRUNC(SYSDATE);
    END cloturer_adhesions_expirees;

    PROCEDURE marquer_tournois_termines IS
        v_statut_en_cours statut_tournoi.identifiant_statut_tournoi%TYPE;
        v_statut_termine statut_tournoi.identifiant_statut_tournoi%TYPE;
    BEGIN
        SELECT identifiant_statut_tournoi
          INTO v_statut_en_cours
          FROM statut_tournoi
         WHERE code_statut = 'en_cours';

        SELECT identifiant_statut_tournoi
          INTO v_statut_termine
          FROM statut_tournoi
         WHERE code_statut = 'termine';

        UPDATE tournoi_club
           SET identifiant_statut_tournoi = v_statut_termine,
               mis_a_jour_le = SYSTIMESTAMP
         WHERE identifiant_statut_tournoi = v_statut_en_cours
           AND date_fin < TRUNC(SYSDATE);
    END marquer_tournois_termines;

    PROCEDURE lancer_maintenance_quotidienne IS
    BEGIN
        cloturer_droits_media_expires;
        archiver_articles_en_attente_anciens;
        expirer_catalogue_boutique;
        purger_anciens_consentements_visiteurs;
        cloturer_adhesions_expirees;
        marquer_tournois_termines;
        COMMIT;
    END lancer_maintenance_quotidienne;
END pkg_maintenance_site;
/

BEGIN
    BEGIN
        DBMS_SCHEDULER.DROP_JOB(
            job_name => 'JOB_MAINTENANCE_QUOTIDIENNE_SITE',
            force => TRUE
        );
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -27475 THEN
                RAISE;
            END IF;
    END;

    DBMS_SCHEDULER.CREATE_JOB(
        job_name => 'JOB_MAINTENANCE_QUOTIDIENNE_SITE',
        job_type => 'PLSQL_BLOCK',
        job_action => 'BEGIN pkg_maintenance_site.lancer_maintenance_quotidienne; END;',
        start_date => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY;BYHOUR=02;BYMINUTE=00;BYSECOND=00',
        enabled => TRUE,
        comments => 'Maintenance auto quotidienne du site du club echecs'
    );
END;
/

