<?php

declare(strict_types=1);

$racineProjet = dirname(__DIR__);
$echecs = [];

function verifier(bool $condition, string $message): void
{
    global $echecs;

    if (!$condition) {
        $echecs[] = $message;
    }
}

function contenu_fichier_obligatoire(string $chemin): string
{
    $contenu = file_get_contents($chemin);

    if ($contenu === false) {
        throw new RuntimeException('Lecture impossible: ' . $chemin);
    }

    return $contenu;
}

$index = contenu_fichier_obligatoire($racineProjet . '/index.php');

verifier(!str_contains($index, 'new StockageJson'), 'index.php ne doit plus instancier le stockage JSON metier.');
verifier(!preg_match('/donnees[\\\\\/][a-z_]+\.json/', $index), 'index.php ne doit plus pointer vers les fichiers JSON metier.');
verifier(str_contains($index, 'BaseDeDonneesOracle::depuisEnvironnement'), 'index.php doit construire les depots depuis Oracle.');
verifier(!str_contains($index, '/donnees/cache/'), 'index.php ne doit plus configurer de cache JSON dans donnees/cache.');

$schemaOracle10g = contenu_fichier_obligatoire($racineProjet . '/base_de_donnees/oracle/10g/schema.sql');
$schemaMinuscule = strtolower($schemaOracle10g);

verifier(str_contains($schemaMinuscule, 'create table compte_membre'), 'Le schema Oracle 10g doit definir compte_membre.');
verifier(str_contains($schemaMinuscule, 'primary key'), 'Le schema Oracle 10g doit definir des cles primaires.');
verifier(str_contains($schemaMinuscule, 'foreign key'), 'Le schema Oracle 10g doit definir des cles etrangeres.');
verifier(str_contains($schemaMinuscule, 'schema_migration'), 'Le schema Oracle 10g doit tracer les migrations.');
verifier(str_contains($schemaMinuscule, 'audit_changement_base'), 'Le schema Oracle 10g doit tracer les changements ulterieurs.');
verifier(!str_contains($schemaMinuscule, 'generated by default as identity'), 'Oracle 10g ne supporte pas les colonnes IDENTITY.');
verifier(!str_contains($schemaMinuscule, 'fetch first'), 'Oracle 10g ne supporte pas FETCH FIRST.');
verifier(!str_contains($schemaMinuscule, ' offset '), 'Oracle 10g ne supporte pas OFFSET.');

$migrations = glob($racineProjet . '/base_de_donnees/oracle/10g/migrations/*.sql') ?: [];
verifier(count($migrations) >= 6, 'Les migrations Oracle 10g doivent etre separees par categorie.');

$verificationSecurite = contenu_fichier_obligatoire($racineProjet . '/base_de_donnees/oracle/10g/security_verify.sql');
$verificationMinuscule = strtolower($verificationSecurite);
verifier(str_contains($verificationMinuscule, 'user_tab_privs_made'), 'La verification securite doit inspecter les privileges sortants.');
verifier(str_contains($verificationMinuscule, 'user_constraints'), 'La verification securite doit inspecter les contraintes.');
verifier(str_contains($verificationMinuscule, 'user_indexes'), 'La verification securite doit inspecter les index.');
verifier(!str_contains($verificationMinuscule, 'grant dba'), 'Aucun script de securite ne doit recommander GRANT DBA.');

$journalChangements = contenu_fichier_obligatoire($racineProjet . '/base_de_donnees/oracle/10g/change_journal_template.sql');
foreach (['CHECK', 'PLAN', 'APPLY', 'VERIFY', 'ROLLBACK'] as $section) {
    verifier(str_contains($journalChangements, $section), 'Le modele de changement doit contenir la section ' . $section . '.');
}

$htaccessRacine = contenu_fichier_obligatoire($racineProjet . '/.htaccess');
$htaccessDonnees = contenu_fichier_obligatoire($racineProjet . '/donnees/.htaccess');
$htaccessRuntime = contenu_fichier_obligatoire($racineProjet . '/stockage_runtime/.htaccess');
$htaccessUploads = contenu_fichier_obligatoire($racineProjet . '/ressources/media/uploads/.htaccess');

verifier(str_contains($htaccessRacine, 'Options -Indexes'), 'La racine Apache doit desactiver le listing.');
verifier(str_contains($htaccessDonnees, 'Require all denied'), 'Le dossier donnees doit etre inaccessible en HTTP.');
verifier(str_contains($htaccessRuntime, 'Require all denied'), 'Le dossier stockage_runtime doit etre inaccessible en HTTP.');
verifier(str_contains($htaccessUploads, 'FilesMatch'), 'Le dossier uploads doit bloquer les scripts executables.');
verifier(str_contains($htaccessUploads, 'php|phtml|phar'), 'Les uploads doivent bloquer les extensions PHP.');

if ($echecs !== []) {
    fwrite(STDERR, "Echecs Oracle-only runtime:\n");

    foreach ($echecs as $echec) {
        fwrite(STDERR, '- ' . $echec . "\n");
    }

    exit(1);
}

echo "Runtime Oracle-only et durcissement Apache OK.\n";
