PROMPT [2.0.2] Accounts and governance

CREATE TABLE compte_membre (
    identifiant_compte_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adresse_courriel VARCHAR2(320 CHAR) NOT NULL,
    mot_de_passe_hache VARCHAR2(255 CHAR) NOT NULL,
    identifiant_statut_compte NUMBER NOT NULL,
    courriel_verifie_le TIMESTAMP WITH TIME ZONE NULL,
    derniere_connexion_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_compte_membre_statut
        FOREIGN KEY (identifiant_statut_compte)
        REFERENCES ref_statut_compte (identifiant_statut_compte)
);

CREATE UNIQUE INDEX uq_compte_membre_email_lower
    ON compte_membre (LOWER(adresse_courriel));

CREATE TABLE profil_membre (
    identifiant_profil_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    prenom VARCHAR2(100 CHAR) NOT NULL,
    nom VARCHAR2(100 CHAR) NOT NULL,
    date_naissance DATE NULL,
    biographie CLOB NULL,
    pseudo_chess_com VARCHAR2(50 CHAR) NULL,
    accepte_affichage_public_profil CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_profil_membre_compte UNIQUE (identifiant_compte_membre),
    CONSTRAINT ck_profil_membre_public CHECK (accepte_affichage_public_profil IN ('Y', 'N')),
    CONSTRAINT fk_profil_membre_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE UNIQUE INDEX uq_profil_membre_pseudo_chess_lower
    ON profil_membre (CASE WHEN pseudo_chess_com IS NOT NULL THEN LOWER(pseudo_chess_com) END);

CREATE TABLE compte_role (
    identifiant_compte_role NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_role_compte NUMBER NOT NULL,
    attribue_par_identifiant_compte NUMBER NULL,
    debut_effet DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    fin_effet DATE NULL,
    commentaire_attribution VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_compte_role_periode UNIQUE (
        identifiant_compte_membre,
        identifiant_role_compte,
        debut_effet
    ),
    CONSTRAINT ck_compte_role_dates CHECK (fin_effet IS NULL OR fin_effet >= debut_effet),
    CONSTRAINT fk_compte_role_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_compte_role_role
        FOREIGN KEY (identifiant_role_compte)
        REFERENCES ref_role_compte (identifiant_role_compte),
    CONSTRAINT fk_compte_role_operateur
        FOREIGN KEY (attribue_par_identifiant_compte)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE classement_membre (
    identifiant_classement_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_type_classement NUMBER NOT NULL,
    valeur_classement NUMBER(5) NOT NULL,
    source_classement VARCHAR2(40 CHAR) DEFAULT 'manuel' NOT NULL,
    mesure_le DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    est_valeur_active CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_classement_membre_mesure UNIQUE (
        identifiant_compte_membre,
        identifiant_type_classement,
        mesure_le
    ),
    CONSTRAINT ck_classement_membre_valeur CHECK (valeur_classement BETWEEN 100 AND 3500),
    CONSTRAINT ck_classement_membre_actif CHECK (est_valeur_active IN ('Y', 'N')),
    CONSTRAINT fk_classement_membre_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_classement_membre_type
        FOREIGN KEY (identifiant_type_classement)
        REFERENCES ref_type_classement (identifiant_type_classement)
);

CREATE UNIQUE INDEX uq_classement_membre_actif
    ON classement_membre (
        CASE WHEN est_valeur_active = 'Y' THEN identifiant_compte_membre END,
        CASE WHEN est_valeur_active = 'Y' THEN identifiant_type_classement END
    );

CREATE TABLE consentement_membre (
    identifiant_consentement_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_type_consentement NUMBER NOT NULL,
    identifiant_document_juridique_version NUMBER NOT NULL,
    accepte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_consentement_membre_version UNIQUE (
        identifiant_compte_membre,
        identifiant_type_consentement,
        identifiant_document_juridique_version
    ),
    CONSTRAINT fk_consentement_membre_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_consentement_membre_type
        FOREIGN KEY (identifiant_type_consentement)
        REFERENCES ref_type_consentement (identifiant_type_consentement),
    CONSTRAINT fk_consentement_membre_document
        FOREIGN KEY (identifiant_document_juridique_version)
        REFERENCES document_juridique_version (identifiant_document_juridique_version)
);

CREATE TABLE consentement_cookie_visiteur (
    identifiant_consentement_cookie_visiteur NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jeton_consentement VARCHAR2(128 CHAR) NOT NULL,
    identifiant_document_juridique_version NUMBER NULL,
    choix_theme VARCHAR2(10 CHAR) NULL,
    accepte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_cookie_visiteur_jeton UNIQUE (jeton_consentement),
    CONSTRAINT fk_cookie_visiteur_document
        FOREIGN KEY (identifiant_document_juridique_version)
        REFERENCES document_juridique_version (identifiant_document_juridique_version)
);

CREATE TABLE journal_connexion (
    identifiant_journal_connexion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NULL,
    adresse_courriel_tentee VARCHAR2(320 CHAR) NULL,
    connecte_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    adresse_ip VARCHAR2(64 CHAR) NULL,
    agent_utilisateur VARCHAR2(400 CHAR) NULL,
    succes CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    motif_echec VARCHAR2(200 CHAR) NULL,
    CONSTRAINT ck_journal_connexion_succes CHECK (succes IN ('Y', 'N')),
    CONSTRAINT fk_journal_connexion_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE INDEX idx_compte_role_compte ON compte_role (identifiant_compte_membre);
CREATE INDEX idx_compte_role_role ON compte_role (identifiant_role_compte);
CREATE INDEX idx_classement_membre_compte ON classement_membre (identifiant_compte_membre);
CREATE INDEX idx_consentement_membre_compte ON consentement_membre (identifiant_compte_membre);
CREATE INDEX idx_journal_connexion_compte ON journal_connexion (identifiant_compte_membre);

INSERT INTO schema_migration (version_schema, description_migration, type_migration)
VALUES ('2.0.2', 'Accounts, profile, role assignments, legal proofs and login journal', 'schema');

COMMIT;
