PROMPT [2.0.1] Reference tables

CREATE TABLE ref_role_compte (
    identifiant_role_compte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_role VARCHAR2(30 CHAR) NOT NULL,
    libelle_role VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_role_compte_code UNIQUE (code_role),
    CONSTRAINT uq_ref_role_compte_ordre UNIQUE (ordre_affichage)
);

CREATE TABLE ref_statut_compte (
    identifiant_statut_compte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_compte_code UNIQUE (code_statut)
);

CREATE TABLE ref_type_consentement (
    identifiant_type_consentement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_consentement VARCHAR2(50 CHAR) NOT NULL,
    libelle_consentement VARCHAR2(150 CHAR) NOT NULL,
    base_legale VARCHAR2(150 CHAR) NOT NULL,
    duree_conservation_mois NUMBER(4) NOT NULL,
    est_obligatoire CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_type_consentement_code UNIQUE (code_consentement),
    CONSTRAINT ck_ref_type_consentement_obligatoire CHECK (est_obligatoire IN ('Y', 'N'))
);

CREATE TABLE ref_statut_article (
    identifiant_statut_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_article_code UNIQUE (code_statut)
);

CREATE TABLE ref_decision_revision_article (
    identifiant_decision_revision_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_decision VARCHAR2(40 CHAR) NOT NULL,
    libelle_decision VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_decision_revision_article_code UNIQUE (code_decision)
);

CREATE TABLE ref_type_media (
    identifiant_type_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_media VARCHAR2(30 CHAR) NOT NULL,
    libelle_type_media VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_type_media_code UNIQUE (code_type_media)
);

CREATE TABLE ref_mode_stockage_media (
    identifiant_mode_stockage_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_mode_stockage VARCHAR2(30 CHAR) NOT NULL,
    libelle_mode_stockage VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_mode_stockage_media_code UNIQUE (code_mode_stockage)
);

CREATE TABLE ref_statut_media (
    identifiant_statut_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_media_code UNIQUE (code_statut)
);

CREATE TABLE ref_statut_droits_media (
    identifiant_statut_droits_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_droits_media_code UNIQUE (code_statut)
);

CREATE TABLE ref_categorie_produit (
    identifiant_categorie_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_categorie VARCHAR2(30 CHAR) NOT NULL,
    libelle_categorie VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_categorie_produit_code UNIQUE (code_categorie)
);

CREATE TABLE ref_statut_produit (
    identifiant_statut_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_produit_code UNIQUE (code_statut)
);

CREATE TABLE ref_statut_commande (
    identifiant_statut_commande NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(30 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_commande_code UNIQUE (code_statut)
);

CREATE TABLE ref_type_adhesion (
    identifiant_type_adhesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_adhesion VARCHAR2(30 CHAR) NOT NULL,
    libelle_type_adhesion VARCHAR2(100 CHAR) NOT NULL,
    montant_base NUMBER(10,2) DEFAULT 0 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_type_adhesion_code UNIQUE (code_type_adhesion),
    CONSTRAINT ck_ref_type_adhesion_montant CHECK (montant_base >= 0)
);

CREATE TABLE ref_statut_adhesion (
    identifiant_statut_adhesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_adhesion_code UNIQUE (code_statut)
);

CREATE TABLE ref_type_activite (
    identifiant_type_activite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_activite VARCHAR2(40 CHAR) NOT NULL,
    libelle_type_activite VARCHAR2(120 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_type_activite_code UNIQUE (code_type_activite)
);

CREATE TABLE ref_niveau_joueur (
    identifiant_niveau_joueur NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_niveau VARCHAR2(30 CHAR) NOT NULL,
    libelle_niveau VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_niveau_joueur_code UNIQUE (code_niveau),
    CONSTRAINT uq_ref_niveau_joueur_ordre UNIQUE (ordre_affichage)
);

CREATE TABLE ref_statut_inscription_session (
    identifiant_statut_inscription_session NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_inscription_session_code UNIQUE (code_statut)
);

CREATE TABLE ref_statut_tournoi (
    identifiant_statut_tournoi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_tournoi_code UNIQUE (code_statut)
);

CREATE TABLE ref_statut_inscription_tournoi (
    identifiant_statut_inscription_tournoi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_statut VARCHAR2(40 CHAR) NOT NULL,
    libelle_statut VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_statut_inscription_tournoi_code UNIQUE (code_statut)
);

CREATE TABLE ref_type_classement (
    identifiant_type_classement NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_type_classement VARCHAR2(30 CHAR) NOT NULL,
    libelle_type_classement VARCHAR2(100 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) DEFAULT 100 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_ref_type_classement_code UNIQUE (code_type_classement),
    CONSTRAINT uq_ref_type_classement_ordre UNIQUE (ordre_affichage)
);

INSERT INTO schema_migration (version_schema, description_migration, type_migration)
VALUES ('2.0.1', 'Reference tables for security, content, commerce and club operations', 'schema');

COMMIT;
