PROMPT [2.0.4] Commerce and club operations

CREATE TABLE produit (
    identifiant_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_categorie_produit NUMBER NOT NULL,
    identifiant_statut_produit NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    reference_stock VARCHAR2(80 CHAR) NULL,
    description_courte VARCHAR2(500 CHAR) NOT NULL,
    description_longue CLOB NULL,
    quantite_stock NUMBER(10) DEFAULT 0 NOT NULL,
    disponible_a_partir_de TIMESTAMP WITH TIME ZONE NULL,
    disponible_jusqua TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_produit_slug UNIQUE (slug),
    CONSTRAINT uq_produit_reference_stock UNIQUE (reference_stock),
    CONSTRAINT ck_produit_stock CHECK (quantite_stock >= 0),
    CONSTRAINT ck_produit_dates CHECK (disponible_jusqua IS NULL OR disponible_a_partir_de IS NULL OR disponible_jusqua >= disponible_a_partir_de),
    CONSTRAINT fk_produit_categorie
        FOREIGN KEY (identifiant_categorie_produit)
        REFERENCES ref_categorie_produit (identifiant_categorie_produit),
    CONSTRAINT fk_produit_statut
        FOREIGN KEY (identifiant_statut_produit)
        REFERENCES ref_statut_produit (identifiant_statut_produit)
);

CREATE TABLE prix_produit (
    identifiant_prix_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_produit NUMBER NOT NULL,
    code_devise CHAR(3 CHAR) NOT NULL,
    montant NUMBER(10,2) NOT NULL,
    applicable_a_partir_de TIMESTAMP WITH TIME ZONE NOT NULL,
    applicable_jusqua TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_prix_produit UNIQUE (identifiant_produit, code_devise, applicable_a_partir_de),
    CONSTRAINT ck_prix_produit_montant CHECK (montant >= 0),
    CONSTRAINT ck_prix_produit_dates CHECK (applicable_jusqua IS NULL OR applicable_jusqua >= applicable_a_partir_de),
    CONSTRAINT fk_prix_produit_produit
        FOREIGN KEY (identifiant_produit)
        REFERENCES produit (identifiant_produit)
);

CREATE UNIQUE INDEX uq_prix_produit_actif
    ON prix_produit (
        CASE WHEN applicable_jusqua IS NULL THEN identifiant_produit END,
        CASE WHEN applicable_jusqua IS NULL THEN code_devise END
    );

CREATE TABLE media_produit (
    identifiant_media_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_produit NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_produit UNIQUE (identifiant_produit, identifiant_ressource_media),
    CONSTRAINT fk_media_produit_produit
        FOREIGN KEY (identifiant_produit)
        REFERENCES produit (identifiant_produit),
    CONSTRAINT fk_media_produit_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE commande_client (
    identifiant_commande_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NULL,
    identifiant_statut_commande NUMBER NOT NULL,
    reference_commande VARCHAR2(50 CHAR) NOT NULL,
    nom_facturation VARCHAR2(200 CHAR) NOT NULL,
    courriel_facturation VARCHAR2(320 CHAR) NOT NULL,
    code_devise CHAR(3 CHAR) NOT NULL,
    commandee_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    payee_le TIMESTAMP WITH TIME ZONE NULL,
    annulee_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_commande_client_reference UNIQUE (reference_commande),
    CONSTRAINT fk_commande_client_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_commande_client_statut
        FOREIGN KEY (identifiant_statut_commande)
        REFERENCES ref_statut_commande (identifiant_statut_commande)
);

CREATE TABLE ligne_commande_client (
    identifiant_ligne_commande_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_commande_client NUMBER NOT NULL,
    identifiant_produit NUMBER NOT NULL,
    quantite NUMBER(10) NOT NULL,
    prix_unitaire NUMBER(10,2) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_ligne_commande_client_quantite CHECK (quantite > 0),
    CONSTRAINT ck_ligne_commande_client_prix CHECK (prix_unitaire >= 0),
    CONSTRAINT fk_ligne_commande_client_commande
        FOREIGN KEY (identifiant_commande_client)
        REFERENCES commande_client (identifiant_commande_client),
    CONSTRAINT fk_ligne_commande_client_produit
        FOREIGN KEY (identifiant_produit)
        REFERENCES produit (identifiant_produit)
);

CREATE TABLE saison_club (
    identifiant_saison_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_saison VARCHAR2(20 CHAR) NOT NULL,
    libelle_saison VARCHAR2(120 CHAR) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    est_saison_active CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_saison_club_code UNIQUE (code_saison),
    CONSTRAINT ck_saison_club_active CHECK (est_saison_active IN ('Y', 'N')),
    CONSTRAINT ck_saison_club_dates CHECK (date_fin >= date_debut)
);

CREATE UNIQUE INDEX uq_saison_club_active
    ON saison_club (
        CASE WHEN est_saison_active = 'Y' THEN 1 END
    );

CREATE TABLE adhesion_membre (
    identifiant_adhesion_membre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_saison_club NUMBER NOT NULL,
    identifiant_type_adhesion NUMBER NOT NULL,
    identifiant_statut_adhesion NUMBER NOT NULL,
    date_debut DATE NOT NULL,
    date_expiration DATE NOT NULL,
    montant_attendu NUMBER(10,2) NOT NULL,
    montant_paye NUMBER(10,2) DEFAULT 0 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_adhesion_membre_saison UNIQUE (identifiant_compte_membre, identifiant_saison_club),
    CONSTRAINT ck_adhesion_membre_dates CHECK (date_expiration >= date_debut),
    CONSTRAINT ck_adhesion_membre_montants CHECK (montant_attendu >= 0 AND montant_paye >= 0),
    CONSTRAINT fk_adhesion_membre_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_adhesion_membre_saison
        FOREIGN KEY (identifiant_saison_club)
        REFERENCES saison_club (identifiant_saison_club),
    CONSTRAINT fk_adhesion_membre_type
        FOREIGN KEY (identifiant_type_adhesion)
        REFERENCES ref_type_adhesion (identifiant_type_adhesion),
    CONSTRAINT fk_adhesion_membre_statut
        FOREIGN KEY (identifiant_statut_adhesion)
        REFERENCES ref_statut_adhesion (identifiant_statut_adhesion)
);

CREATE TABLE paiement_adhesion (
    identifiant_paiement_adhesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_adhesion_membre NUMBER NOT NULL,
    reference_paiement VARCHAR2(80 CHAR) NOT NULL,
    montant NUMBER(10,2) NOT NULL,
    mode_paiement VARCHAR2(40 CHAR) NOT NULL,
    recu_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_paiement_adhesion_reference UNIQUE (reference_paiement),
    CONSTRAINT ck_paiement_adhesion_montant CHECK (montant > 0),
    CONSTRAINT fk_paiement_adhesion_adhesion
        FOREIGN KEY (identifiant_adhesion_membre)
        REFERENCES adhesion_membre (identifiant_adhesion_membre)
);

CREATE TABLE activite_club (
    identifiant_activite_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_type_activite NUMBER NOT NULL,
    identifiant_niveau_joueur_minimum NUMBER NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    description_activite CLOB NULL,
    est_visible_publiquement CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_activite_club_visible CHECK (est_visible_publiquement IN ('Y', 'N')),
    CONSTRAINT fk_activite_club_type
        FOREIGN KEY (identifiant_type_activite)
        REFERENCES ref_type_activite (identifiant_type_activite),
    CONSTRAINT fk_activite_club_niveau
        FOREIGN KEY (identifiant_niveau_joueur_minimum)
        REFERENCES ref_niveau_joueur (identifiant_niveau_joueur)
);

CREATE TABLE session_activite (
    identifiant_session_activite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_activite_club NUMBER NOT NULL,
    identifiant_compte_responsable NUMBER NULL,
    date_debut TIMESTAMP WITH TIME ZONE NOT NULL,
    date_fin TIMESTAMP WITH TIME ZONE NOT NULL,
    lieu VARCHAR2(200 CHAR) NOT NULL,
    places_max NUMBER(6) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_session_activite_dates CHECK (date_fin >= date_debut),
    CONSTRAINT ck_session_activite_places CHECK (places_max IS NULL OR places_max > 0),
    CONSTRAINT fk_session_activite_activite
        FOREIGN KEY (identifiant_activite_club)
        REFERENCES activite_club (identifiant_activite_club),
    CONSTRAINT fk_session_activite_responsable
        FOREIGN KEY (identifiant_compte_responsable)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE inscription_session_activite (
    identifiant_inscription_session_activite NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_session_activite NUMBER NOT NULL,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_statut_inscription_session NUMBER NOT NULL,
    inscrit_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_inscription_session_activite UNIQUE (identifiant_session_activite, identifiant_compte_membre),
    CONSTRAINT fk_inscription_session_activite_session
        FOREIGN KEY (identifiant_session_activite)
        REFERENCES session_activite (identifiant_session_activite),
    CONSTRAINT fk_inscription_session_activite_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_inscription_session_activite_statut
        FOREIGN KEY (identifiant_statut_inscription_session)
        REFERENCES ref_statut_inscription_session (identifiant_statut_inscription_session)
);

CREATE TABLE tournoi_club (
    identifiant_tournoi_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_statut_tournoi NUMBER NOT NULL,
    identifiant_compte_organisateur NUMBER NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    lieu VARCHAR2(200 CHAR) NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    cadence_tournoi VARCHAR2(60 CHAR) NULL,
    description_tournoi CLOB NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_tournoi_club_dates CHECK (date_fin >= date_debut),
    CONSTRAINT fk_tournoi_club_statut
        FOREIGN KEY (identifiant_statut_tournoi)
        REFERENCES ref_statut_tournoi (identifiant_statut_tournoi),
    CONSTRAINT fk_tournoi_club_organisateur
        FOREIGN KEY (identifiant_compte_organisateur)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE inscription_tournoi_club (
    identifiant_inscription_tournoi_club NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_tournoi_club NUMBER NOT NULL,
    identifiant_compte_membre NUMBER NOT NULL,
    identifiant_statut_inscription_tournoi NUMBER NOT NULL,
    elo_inscription NUMBER(5) NULL,
    inscrit_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_inscription_tournoi_club UNIQUE (identifiant_tournoi_club, identifiant_compte_membre),
    CONSTRAINT ck_inscription_tournoi_club_elo CHECK (elo_inscription IS NULL OR elo_inscription BETWEEN 100 AND 3500),
    CONSTRAINT fk_inscription_tournoi_club_tournoi
        FOREIGN KEY (identifiant_tournoi_club)
        REFERENCES tournoi_club (identifiant_tournoi_club),
    CONSTRAINT fk_inscription_tournoi_club_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_inscription_tournoi_club_statut
        FOREIGN KEY (identifiant_statut_inscription_tournoi)
        REFERENCES ref_statut_inscription_tournoi (identifiant_statut_inscription_tournoi)
);

CREATE TABLE rencontre_interclub (
    identifiant_rencontre_interclub NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_saison_club NUMBER NOT NULL,
    equipe_adverse VARCHAR2(200 CHAR) NOT NULL,
    date_rencontre DATE NOT NULL,
    lieu VARCHAR2(200 CHAR) NULL,
    score_club NUMBER(4,1) NULL,
    score_adverse NUMBER(4,1) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rencontre_interclub_saison
        FOREIGN KEY (identifiant_saison_club)
        REFERENCES saison_club (identifiant_saison_club)
);

CREATE TABLE participation_rencontre_interclub (
    identifiant_participation_rencontre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_rencontre_interclub NUMBER NOT NULL,
    identifiant_compte_membre NUMBER NOT NULL,
    couleur_jouee VARCHAR2(5 CHAR) NULL,
    resultat_partie VARCHAR2(20 CHAR) NULL,
    echiquier_numero NUMBER(4) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_participation_rencontre_interclub UNIQUE (
        identifiant_rencontre_interclub,
        identifiant_compte_membre
    ),
    CONSTRAINT fk_participation_rencontre_interclub_rencontre
        FOREIGN KEY (identifiant_rencontre_interclub)
        REFERENCES rencontre_interclub (identifiant_rencontre_interclub),
    CONSTRAINT fk_participation_rencontre_interclub_compte
        FOREIGN KEY (identifiant_compte_membre)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE message_contact (
    identifiant_message_contact NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_expediteur VARCHAR2(150 CHAR) NOT NULL,
    courriel_expediteur VARCHAR2(320 CHAR) NOT NULL,
    sujet_message VARCHAR2(200 CHAR) NOT NULL,
    contenu_message CLOB NOT NULL,
    traite_par_identifiant_compte NUMBER NULL,
    traite_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_message_contact_operateur
        FOREIGN KEY (traite_par_identifiant_compte)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE INDEX idx_commande_client_compte ON commande_client (identifiant_compte_membre);
CREATE INDEX idx_commande_client_statut ON commande_client (identifiant_statut_commande);
CREATE INDEX idx_adhesion_membre_compte ON adhesion_membre (identifiant_compte_membre);
CREATE INDEX idx_adhesion_membre_saison ON adhesion_membre (identifiant_saison_club);
CREATE INDEX idx_session_activite_activite ON session_activite (identifiant_activite_club);
CREATE INDEX idx_inscription_session_activite_compte ON inscription_session_activite (identifiant_compte_membre);
CREATE INDEX idx_inscription_tournoi_club_compte ON inscription_tournoi_club (identifiant_compte_membre);

INSERT INTO schema_migration (version_schema, description_migration, type_migration)
VALUES ('2.0.4', 'Commerce, memberships, activities, tournaments and contact tables', 'schema');

COMMIT;
