PROMPT [2.0.7] Structured article editor blocks

CREATE TABLE ref_type_bloc_article (
    code_type_bloc VARCHAR2(30 CHAR) PRIMARY KEY,
    libelle_type_bloc VARCHAR2(80 CHAR) NOT NULL,
    ordre_affichage NUMBER(4) NOT NULL,
    accepte_texte CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    accepte_media CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    CONSTRAINT ck_ref_type_bloc_article_texte CHECK (accepte_texte IN ('Y', 'N')),
    CONSTRAINT ck_ref_type_bloc_article_media CHECK (accepte_media IN ('Y', 'N'))
);

INSERT INTO ref_type_bloc_article (code_type_bloc, libelle_type_bloc, ordre_affichage, accepte_texte, accepte_media)
VALUES ('paragraphe', 'Paragraphe', 10, 'Y', 'N');

INSERT INTO ref_type_bloc_article (code_type_bloc, libelle_type_bloc, ordre_affichage, accepte_texte, accepte_media)
VALUES ('sous_titre', 'Sous-titre', 20, 'Y', 'N');

INSERT INTO ref_type_bloc_article (code_type_bloc, libelle_type_bloc, ordre_affichage, accepte_texte, accepte_media)
VALUES ('image', 'Image ou GIF', 30, 'N', 'Y');

INSERT INTO ref_type_bloc_article (code_type_bloc, libelle_type_bloc, ordre_affichage, accepte_texte, accepte_media)
VALUES ('video', 'Video', 40, 'N', 'Y');

ALTER TABLE article ADD (
    auteur_affiche VARCHAR2(120 CHAR) DEFAULT 'Auteur club' NOT NULL
);

CREATE TABLE article_bloc (
    identifiant_article_bloc NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    code_type_bloc VARCHAR2(30 CHAR) NOT NULL,
    identifiant_ressource_media NUMBER NULL,
    ordre_affichage NUMBER(6) NOT NULL,
    texte CLOB NULL,
    texte_alternatif VARCHAR2(180 CHAR) NULL,
    legende VARCHAR2(220 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_article_bloc_ordre UNIQUE (identifiant_article, ordre_affichage),
    CONSTRAINT ck_article_bloc_ordre CHECK (ordre_affichage > 0),
    CONSTRAINT ck_article_bloc_contenu CHECK (
        (
            code_type_bloc IN ('paragraphe', 'sous_titre')
            AND texte IS NOT NULL
            AND identifiant_ressource_media IS NULL
        )
        OR
        (
            code_type_bloc IN ('image', 'video')
            AND identifiant_ressource_media IS NOT NULL
            AND texte IS NULL
            AND texte_alternatif IS NOT NULL
        )
    ),
    CONSTRAINT fk_article_bloc_article
        FOREIGN KEY (identifiant_article)
        REFERENCES article (identifiant_article)
        ON DELETE CASCADE,
    CONSTRAINT fk_article_bloc_type
        FOREIGN KEY (code_type_bloc)
        REFERENCES ref_type_bloc_article (code_type_bloc),
    CONSTRAINT fk_article_bloc_media
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE INDEX idx_article_bloc_article ON article_bloc (identifiant_article, ordre_affichage);
CREATE INDEX idx_article_bloc_media ON article_bloc (identifiant_ressource_media);

CREATE OR REPLACE VIEW vw_article_blocs_ordonnes AS
SELECT ab.identifiant_article_bloc,
       ab.identifiant_article,
       a.titre AS article_titre,
       a.auteur_affiche,
       ab.ordre_affichage,
       ab.code_type_bloc,
       rtba.libelle_type_bloc,
       ab.texte,
       ab.texte_alternatif,
       ab.legende,
       rm.identifiant_ressource_media,
       rm.titre AS media_titre,
       rm.type_mime,
       rm.nom_fichier_original,
       rem.uri_stockage
  FROM article_bloc ab
  JOIN article a
    ON a.identifiant_article = ab.identifiant_article
  JOIN ref_type_bloc_article rtba
    ON rtba.code_type_bloc = ab.code_type_bloc
  LEFT JOIN ressource_media rm
    ON rm.identifiant_ressource_media = ab.identifiant_ressource_media
  LEFT JOIN reference_externe_media rem
    ON rem.identifiant_ressource_media = rm.identifiant_ressource_media;
/

CREATE OR REPLACE VIEW vw_admin_articles AS
SELECT a.identifiant_article,
       a.titre,
       a.slug,
       a.resume,
       a.auteur_affiche,
       rsa.code_statut,
       rsa.libelle_statut,
       a.soumis_le,
       a.publie_le,
       a.cree_le,
       a.mis_a_jour_le,
       cm.adresse_courriel AS auteur_courriel,
       pm.prenom,
       pm.nom,
       COUNT(DISTINCT ra.identifiant_revision_article) AS total_revisions,
       COUNT(DISTINCT ab.identifiant_article_bloc) AS total_blocs
  FROM article a
  JOIN ref_statut_article rsa
    ON rsa.identifiant_statut_article = a.identifiant_statut_article
  JOIN compte_membre cm
    ON cm.identifiant_compte_membre = a.identifiant_compte_auteur
  LEFT JOIN profil_membre pm
    ON pm.identifiant_compte_membre = cm.identifiant_compte_membre
  LEFT JOIN revision_article ra
    ON ra.identifiant_article = a.identifiant_article
  LEFT JOIN article_bloc ab
    ON ab.identifiant_article = a.identifiant_article
 GROUP BY a.identifiant_article,
          a.titre,
          a.slug,
          a.resume,
          a.auteur_affiche,
          rsa.code_statut,
          rsa.libelle_statut,
          a.soumis_le,
          a.publie_le,
          a.cree_le,
          a.mis_a_jour_le,
          cm.adresse_courriel,
          pm.prenom,
          pm.nom;
/

CREATE OR REPLACE PACKAGE pkg_article_editor AS
    PROCEDURE creer_article_structure(
        p_identifiant_auteur_compte NUMBER,
        p_auteur_affiche VARCHAR2,
        p_titre VARCHAR2,
        p_resume VARCHAR2,
        p_contenu CLOB,
        o_identifiant_article OUT NUMBER
    );

    PROCEDURE supprimer_blocs_article(
        p_identifiant_article NUMBER
    );

    PROCEDURE ajouter_bloc_texte(
        p_identifiant_article NUMBER,
        p_code_type_bloc VARCHAR2,
        p_ordre_affichage NUMBER,
        p_texte CLOB
    );

    PROCEDURE ajouter_bloc_media(
        p_identifiant_article NUMBER,
        p_code_type_bloc VARCHAR2,
        p_ordre_affichage NUMBER,
        p_identifiant_ressource_media NUMBER,
        p_texte_alternatif VARCHAR2,
        p_legende VARCHAR2 DEFAULT NULL
    );
END pkg_article_editor;
/

CREATE OR REPLACE PACKAGE BODY pkg_article_editor AS
    FUNCTION obtenir_id_statut_article(p_code VARCHAR2) RETURN NUMBER IS
        v_id NUMBER;
    BEGIN
        SELECT identifiant_statut_article
          INTO v_id
          FROM ref_statut_article
         WHERE code_statut = LOWER(TRIM(p_code));

        RETURN v_id;
    END obtenir_id_statut_article;

    FUNCTION generer_slug_article(p_titre VARCHAR2) RETURN VARCHAR2 IS
        v_base VARCHAR2(220 CHAR);
    BEGIN
        v_base := REGEXP_REPLACE(
            REGEXP_REPLACE(LOWER(TRIM(p_titre)), '[^a-z0-9]+', '-'),
            '(^-|-$)',
            ''
        );

        IF v_base IS NULL THEN
            v_base := 'article';
        END IF;

        RETURN SUBSTR(v_base, 1, 180) || '-' || LOWER(SUBSTR(RAWTOHEX(SYS_GUID()), 1, 12));
    END generer_slug_article;

    PROCEDURE creer_article_structure(
        p_identifiant_auteur_compte NUMBER,
        p_auteur_affiche VARCHAR2,
        p_titre VARCHAR2,
        p_resume VARCHAR2,
        p_contenu CLOB,
        o_identifiant_article OUT NUMBER
    ) IS
        v_statut_id NUMBER;
    BEGIN
        IF TRIM(p_titre) IS NULL OR LENGTH(TRIM(p_titre)) > 200 THEN
            RAISE_APPLICATION_ERROR(-20701, 'Titre article invalide.');
        END IF;

        IF TRIM(p_auteur_affiche) IS NULL OR LENGTH(TRIM(p_auteur_affiche)) > 120 THEN
            RAISE_APPLICATION_ERROR(-20702, 'Auteur affiche invalide.');
        END IF;

        IF TRIM(p_resume) IS NULL OR LENGTH(TRIM(p_resume)) > 500 THEN
            RAISE_APPLICATION_ERROR(-20703, 'Resume article invalide.');
        END IF;

        IF p_contenu IS NULL OR DBMS_LOB.GETLENGTH(p_contenu) = 0 THEN
            RAISE_APPLICATION_ERROR(-20710, 'Contenu article obligatoire.');
        END IF;

        v_statut_id := obtenir_id_statut_article('en_attente_validation');

        INSERT INTO article (
            identifiant_compte_auteur,
            identifiant_statut_article,
            auteur_affiche,
            titre,
            slug,
            resume,
            contenu
        ) VALUES (
            p_identifiant_auteur_compte,
            v_statut_id,
            TRIM(p_auteur_affiche),
            TRIM(p_titre),
            generer_slug_article(p_titre),
            TRIM(p_resume),
            p_contenu
        )
        RETURNING identifiant_article INTO o_identifiant_article;
    END creer_article_structure;

    PROCEDURE supprimer_blocs_article(
        p_identifiant_article NUMBER
    ) IS
    BEGIN
        DELETE FROM article_bloc
         WHERE identifiant_article = p_identifiant_article;
    END supprimer_blocs_article;

    PROCEDURE ajouter_bloc_texte(
        p_identifiant_article NUMBER,
        p_code_type_bloc VARCHAR2,
        p_ordre_affichage NUMBER,
        p_texte CLOB
    ) IS
        v_code_type_bloc VARCHAR2(30 CHAR) := LOWER(TRIM(p_code_type_bloc));
    BEGIN
        IF v_code_type_bloc NOT IN ('paragraphe', 'sous_titre') THEN
            RAISE_APPLICATION_ERROR(-20704, 'Type de bloc texte invalide.');
        END IF;

        IF p_texte IS NULL OR DBMS_LOB.GETLENGTH(p_texte) = 0 THEN
            RAISE_APPLICATION_ERROR(-20705, 'Texte de bloc obligatoire.');
        END IF;

        INSERT INTO article_bloc (
            identifiant_article,
            code_type_bloc,
            ordre_affichage,
            texte
        ) VALUES (
            p_identifiant_article,
            v_code_type_bloc,
            p_ordre_affichage,
            p_texte
        );
    END ajouter_bloc_texte;

    PROCEDURE ajouter_bloc_media(
        p_identifiant_article NUMBER,
        p_code_type_bloc VARCHAR2,
        p_ordre_affichage NUMBER,
        p_identifiant_ressource_media NUMBER,
        p_texte_alternatif VARCHAR2,
        p_legende VARCHAR2 DEFAULT NULL
    ) IS
        v_code_type_bloc VARCHAR2(30 CHAR) := LOWER(TRIM(p_code_type_bloc));
        v_code_type_media VARCHAR2(30 CHAR);
    BEGIN
        IF v_code_type_bloc NOT IN ('image', 'video') THEN
            RAISE_APPLICATION_ERROR(-20706, 'Type de bloc media invalide.');
        END IF;

        IF TRIM(p_texte_alternatif) IS NULL OR LENGTH(TRIM(p_texte_alternatif)) > 180 THEN
            RAISE_APPLICATION_ERROR(-20707, 'Texte alternatif media invalide.');
        END IF;

        IF p_legende IS NOT NULL AND LENGTH(TRIM(p_legende)) > 220 THEN
            RAISE_APPLICATION_ERROR(-20708, 'Legende media trop longue.');
        END IF;

        SELECT rtm.code_type_media
          INTO v_code_type_media
          FROM ressource_media rm
          JOIN ref_type_media rtm
            ON rtm.identifiant_type_media = rm.identifiant_type_media
         WHERE rm.identifiant_ressource_media = p_identifiant_ressource_media;

        IF v_code_type_media != v_code_type_bloc THEN
            RAISE_APPLICATION_ERROR(-20709, 'Le type du media ne correspond pas au bloc.');
        END IF;

        INSERT INTO article_bloc (
            identifiant_article,
            code_type_bloc,
            identifiant_ressource_media,
            ordre_affichage,
            texte_alternatif,
            legende
        ) VALUES (
            p_identifiant_article,
            v_code_type_bloc,
            p_identifiant_ressource_media,
            p_ordre_affichage,
            TRIM(p_texte_alternatif),
            NULLIF(TRIM(p_legende), '')
        );
    END ajouter_bloc_media;
END pkg_article_editor;
/

GRANT SELECT ON ref_type_bloc_article TO rl_site_app;
GRANT SELECT ON vw_article_blocs_ordonnes TO rl_site_app;
GRANT EXECUTE ON pkg_article_editor TO rl_site_app;

GRANT SELECT ON ref_type_bloc_article TO rl_site_admin_ops;
GRANT SELECT ON vw_article_blocs_ordonnes TO rl_site_admin_ops;
GRANT SELECT ON vw_admin_articles TO rl_site_admin_ops;
GRANT EXECUTE ON pkg_article_editor TO rl_site_admin_ops;

GRANT SELECT ON ref_type_bloc_article TO rl_site_audit;
GRANT SELECT ON vw_article_blocs_ordonnes TO rl_site_audit;
GRANT SELECT ON vw_admin_articles TO rl_site_audit;

BEGIN
    pkg_schema_migration.enregistrer(
        '2.0.7',
        'Structured article editor blocks and article author display',
        'schema'
    );
END;
/
