PROMPT [2.0.0] Foundation

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'SCHEMA_MIGRATION';

    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20000,
            'SCHEMA_MIGRATION existe deja. Utiliser un schema vide ou une migration compensatrice.'
        );
    END IF;
END;
/

CREATE TABLE schema_migration (
    identifiant_schema_migration NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_schema VARCHAR2(50 CHAR) NOT NULL,
    description_migration VARCHAR2(400 CHAR) NOT NULL,
    type_migration VARCHAR2(20 CHAR) DEFAULT 'schema' NOT NULL,
    applique_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    applique_par VARCHAR2(128 CHAR) DEFAULT USER NOT NULL,
    CONSTRAINT uq_schema_migration_version UNIQUE (version_schema),
    CONSTRAINT ck_schema_migration_type CHECK (type_migration IN ('schema', 'data', 'security', 'seed'))
);

CREATE TABLE journal_audit_administration (
    identifiant_audit_administration NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_operateur NUMBER NULL,
    type_operation VARCHAR2(80 CHAR) NOT NULL,
    objet_cible VARCHAR2(80 CHAR) NOT NULL,
    cle_cible VARCHAR2(120 CHAR) NOT NULL,
    details_operation CLOB NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE parametre_application (
    identifiant_parametre_application NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cle_parametre VARCHAR2(120 CHAR) NOT NULL,
    valeur_parametre VARCHAR2(4000 CHAR) NOT NULL,
    type_parametre VARCHAR2(20 CHAR) DEFAULT 'texte' NOT NULL,
    description_parametre VARCHAR2(500 CHAR) NULL,
    modifiable_par_admin CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_parametre_application_cle UNIQUE (cle_parametre),
    CONSTRAINT ck_parametre_application_type CHECK (type_parametre IN ('texte', 'nombre', 'booleen', 'json')),
    CONSTRAINT ck_parametre_application_admin CHECK (modifiable_par_admin IN ('Y', 'N'))
);

CREATE TABLE type_document_juridique (
    identifiant_type_document_juridique NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_document VARCHAR2(50 CHAR) NOT NULL,
    libelle_document VARCHAR2(150 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_type_document_juridique_code UNIQUE (code_document)
);

CREATE TABLE document_juridique_version (
    identifiant_document_juridique_version NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_type_document_juridique NUMBER NOT NULL,
    version_document VARCHAR2(40 CHAR) NOT NULL,
    titre_document VARCHAR2(200 CHAR) NOT NULL,
    contenu_document CLOB NOT NULL,
    est_version_active CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    publie_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_document_juridique_version UNIQUE (identifiant_type_document_juridique, version_document),
    CONSTRAINT ck_document_juridique_version_active CHECK (est_version_active IN ('Y', 'N')),
    CONSTRAINT fk_document_juridique_type
        FOREIGN KEY (identifiant_type_document_juridique)
        REFERENCES type_document_juridique (identifiant_type_document_juridique)
);

CREATE UNIQUE INDEX uq_document_juridique_version_active
    ON document_juridique_version (
        CASE WHEN est_version_active = 'Y' THEN identifiant_type_document_juridique END
    );

INSERT INTO schema_migration (version_schema, description_migration, type_migration)
VALUES ('2.0.0', 'Foundation v2: schema migration, audit, application parameters and legal documents', 'schema');

COMMIT;
