PROMPT [2.0.3] Content and media

CREATE TABLE article (
    identifiant_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_auteur NUMBER NOT NULL,
    identifiant_statut_article NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    slug VARCHAR2(220 CHAR) NOT NULL,
    resume VARCHAR2(500 CHAR) NOT NULL,
    contenu CLOB NOT NULL,
    soumis_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    publie_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_auteur
        FOREIGN KEY (identifiant_compte_auteur)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_article_statut
        FOREIGN KEY (identifiant_statut_article)
        REFERENCES ref_statut_article (identifiant_statut_article)
);

CREATE TABLE revision_article (
    identifiant_revision_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    identifiant_compte_relecteur NUMBER NOT NULL,
    identifiant_decision_revision_article NUMBER NOT NULL,
    commentaire_revision CLOB NULL,
    decide_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_revision_article_article
        FOREIGN KEY (identifiant_article)
        REFERENCES article (identifiant_article),
    CONSTRAINT fk_revision_article_relecteur
        FOREIGN KEY (identifiant_compte_relecteur)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_revision_article_decision
        FOREIGN KEY (identifiant_decision_revision_article)
        REFERENCES ref_decision_revision_article (identifiant_decision_revision_article)
);

CREATE TABLE ressource_media (
    identifiant_ressource_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_type_media NUMBER NOT NULL,
    identifiant_mode_stockage_media NUMBER NOT NULL,
    identifiant_statut_media NUMBER NOT NULL,
    identifiant_compte_depot NUMBER NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    description_media VARCHAR2(500 CHAR) NULL,
    nom_fichier_original VARCHAR2(255 CHAR) NOT NULL,
    type_mime VARCHAR2(120 CHAR) NOT NULL,
    taille_octets NUMBER(19) NOT NULL,
    largeur_px NUMBER(10) NULL,
    hauteur_px NUMBER(10) NULL,
    duree_secondes NUMBER(10,3) NULL,
    texte_alternatif VARCHAR2(300 CHAR) NULL,
    date_capture DATE NULL,
    valide_par_identifiant_compte NUMBER NULL,
    valide_le TIMESTAMP WITH TIME ZONE NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_ressource_media_taille CHECK (taille_octets >= 0),
    CONSTRAINT fk_ressource_media_type
        FOREIGN KEY (identifiant_type_media)
        REFERENCES ref_type_media (identifiant_type_media),
    CONSTRAINT fk_ressource_media_mode
        FOREIGN KEY (identifiant_mode_stockage_media)
        REFERENCES ref_mode_stockage_media (identifiant_mode_stockage_media),
    CONSTRAINT fk_ressource_media_statut
        FOREIGN KEY (identifiant_statut_media)
        REFERENCES ref_statut_media (identifiant_statut_media),
    CONSTRAINT fk_ressource_media_depot
        FOREIGN KEY (identifiant_compte_depot)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_ressource_media_validateur
        FOREIGN KEY (valide_par_identifiant_compte)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE charge_binaire_media (
    identifiant_charge_binaire_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    charge_binaire BLOB NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_charge_binaire_media_ressource UNIQUE (identifiant_ressource_media),
    CONSTRAINT fk_charge_binaire_media_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE reference_externe_media (
    identifiant_reference_externe_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    fournisseur_stockage VARCHAR2(60 CHAR) NOT NULL,
    uri_stockage VARCHAR2(1000 CHAR) NOT NULL,
    empreinte_sha256 CHAR(64 CHAR) NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_reference_externe_media_ressource UNIQUE (identifiant_ressource_media),
    CONSTRAINT uq_reference_externe_media_uri UNIQUE (uri_stockage),
    CONSTRAINT uq_reference_externe_media_sha UNIQUE (empreinte_sha256),
    CONSTRAINT fk_reference_externe_media_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE autorisation_droits_media (
    identifiant_autorisation_droits_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_statut_droits_media NUMBER NOT NULL,
    nom_titulaire_droits VARCHAR2(200 CHAR) NOT NULL,
    reference_consentement VARCHAR2(200 CHAR) NULL,
    perimetre_autorisation VARCHAR2(200 CHAR) NOT NULL,
    autorise_le TIMESTAMP WITH TIME ZONE NOT NULL,
    expire_le TIMESTAMP WITH TIME ZONE NULL,
    commentaire_revision VARCHAR2(500 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_autorisation_droits_media_dates CHECK (expire_le IS NULL OR expire_le >= autorise_le),
    CONSTRAINT fk_autorisation_droits_media_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_autorisation_droits_media_statut
        FOREIGN KEY (identifiant_statut_droits_media)
        REFERENCES ref_statut_droits_media (identifiant_statut_droits_media)
);

CREATE TABLE revision_media (
    identifiant_revision_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_ressource_media NUMBER NOT NULL,
    identifiant_compte_relecteur NUMBER NOT NULL,
    identifiant_statut_media NUMBER NOT NULL,
    commentaire_revision CLOB NULL,
    decide_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_revision_media_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media),
    CONSTRAINT fk_revision_media_relecteur
        FOREIGN KEY (identifiant_compte_relecteur)
        REFERENCES compte_membre (identifiant_compte_membre),
    CONSTRAINT fk_revision_media_statut
        FOREIGN KEY (identifiant_statut_media)
        REFERENCES ref_statut_media (identifiant_statut_media)
);

CREATE TABLE album_media (
    identifiant_album_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_compte_createur NUMBER NOT NULL,
    titre VARCHAR2(200 CHAR) NOT NULL,
    description_album CLOB NULL,
    est_public CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    mis_a_jour_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_album_media_public CHECK (est_public IN ('Y', 'N')),
    CONSTRAINT fk_album_media_createur
        FOREIGN KEY (identifiant_compte_createur)
        REFERENCES compte_membre (identifiant_compte_membre)
);

CREATE TABLE element_album_media (
    identifiant_element_album_media NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_album_media NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    legende VARCHAR2(300 CHAR) NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_element_album_media UNIQUE (identifiant_album_media, identifiant_ressource_media),
    CONSTRAINT fk_element_album_media_album
        FOREIGN KEY (identifiant_album_media)
        REFERENCES album_media (identifiant_album_media),
    CONSTRAINT fk_element_album_media_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE TABLE media_article (
    identifiant_media_article NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifiant_article NUMBER NOT NULL,
    identifiant_ressource_media NUMBER NOT NULL,
    ordre_affichage NUMBER(6) DEFAULT 1 NOT NULL,
    cree_le TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_media_article UNIQUE (identifiant_article, identifiant_ressource_media),
    CONSTRAINT fk_media_article_article
        FOREIGN KEY (identifiant_article)
        REFERENCES article (identifiant_article),
    CONSTRAINT fk_media_article_ressource
        FOREIGN KEY (identifiant_ressource_media)
        REFERENCES ressource_media (identifiant_ressource_media)
);

CREATE INDEX idx_article_statut ON article (identifiant_statut_article);
CREATE INDEX idx_article_auteur ON article (identifiant_compte_auteur);
CREATE INDEX idx_ressource_media_statut ON ressource_media (identifiant_statut_media);
CREATE INDEX idx_ressource_media_type ON ressource_media (identifiant_type_media);
CREATE INDEX idx_ressource_media_depot ON ressource_media (identifiant_compte_depot);
CREATE INDEX idx_autorisation_droits_media_ressource ON autorisation_droits_media (identifiant_ressource_media);
CREATE INDEX idx_revision_media_ressource ON revision_media (identifiant_ressource_media);

INSERT INTO schema_migration (version_schema, description_migration, type_migration)
VALUES ('2.0.3', 'Editorial and media tables with moderation and rights management', 'schema');

COMMIT;
